### ISSUE TITLE
problem with the readline module 

### ISSUE THREAD

**Issue by mohamedatheer** [entynetproject/ghost#100]
Ok, so every time I try to lunch ghost I get this error 

" Traceback (most recent call last):
  File "./ghost", line 27, in <module>
    import readline
ModuleNotFoundError: No module named 'readline' "

Which is saying that the readline module is not found, so I tried installing the readline module using pip3 in 'cd ghost/'    and it didn't work too and it said the following 

"Requirement already satisfied: readline in /usr/local/lib/python3.7/dist-packages (6.2.4.1)"

I have run out of ideas.....

**Comment by enty8080** [comment]
`apt-get install libreadline`

**Comment by mohamedatheer** [comment]
also didn't work I got the following error...

"Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libreadline"

Do I have to download a package first or something???

**Comment by appcrafted** [comment]
same error, E: Unable to locate package libreadline"

**Comment by enty8080** [comment]
`apt-get search readline`

`apt-get install libreadline-dev`

**Comment by mohamedatheer** [comment]
when I put in the command "apt-get search readline" I got...

"E: Invalid operation search"

and when I put in the command "apt-get install libreadline-dev" I got the same error as last time...

"Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libreadline-dev"

**Comment by enty8080** [comment]
Search for libreadline for your OS in the Internet.

**Comment by game-lover** [comment]
apt update
apt search readline | grep libreadline
apt install libreadline-dev

**Comment by aymenamer691** [comment]
> Ok, so every time I try to lunch ghost I get this error
> 
> " Traceback (most recent call last):
> File "./ghost", line 27, in
> import readline
> ModuleNotFoundError: No module named 'readline' "
> 
> Which is saying that the readline module is not found, so I tried installing the readline module using pip3 in 'cd ghost/' and it didn't work too and it said the following
> 
> "Requirement already satisfied: readline in /usr/local/lib/python3.7/dist-packages (6.2.4.1)"
> 
> I have run out of ideas.....

pip install readline

**Comment by mohamedatheer** [comment]
The issue I had is a a problem with python3.8 and Linux  and not with ghost and or the module. I made a new VM to test my theory and I didn't install python3.8 and I just used the 3.6 version that is pre-installed and it worked perfectly (and all the other versions that may be installed on to kali)...

This is what happened with me and may or may not work with your version of Linux
