### ISSUE TITLE
Failed to connect

### ISSUE THREAD

**Issue by kairosart** [entynetproject/ghost#104]
What the hell! 
Doesn't connect to any device.

Besides, you're closing all the threads without answering anything.

Come on! Be serious.

**Comment by enty8080** [comment]
I am serious, but your not. Man, if program says you `failed to connect` that means **FAILED TO CONNECT**. 🤦‍♂️

**Comment by kairosart** [comment]
I've seen all the closed posts without an answer. That's not really
serious. At least you could explain the bugs and what to do.

**Comment by dhirajwanem** [comment]
bro it fails to connect in any type of ip adress  then what to do what is the work of your tool it fails to connect in each and every ip
