### ISSUE TITLE
Cannot launch applications via ghost launch command

### ISSUE THREAD

**Issue by PSNAppz** [entynetproject/ghost#106]
I tried `launch com.google.android.camera2` which was showing in apps list
But the command returned: `Application is not found!`

Am I doing it wrong?

**Comment by enty8080** [comment]
Hello, I am going to fix this.

**Comment by enty8080** [comment]
Your problem was fixed)) Reclone and reinstall, or update.

**Comment by PSNAppz** [comment]
@enty8080 Thanks
