### ISSUE TITLE
Failed to connect

### ISSUE THREAD

**Issue by TanayBole** [entynetproject/ghost#108]
.-.
    .'   `.
    :0 0  :
    : o    `.
   :         ``.
  :             `.
 :  :         .   `.
 :   :          ` . `.
  `.. :            `. ``;
     `:;             `:'
        :              `.
         `.              `.     
           `'`'`'`---..,___`.

Ghost Framework v5.0
--------------------

ghost> connect 112.164.215.155
[*] Connecting to 112.164.215.155...
[-] Failed to connect to 112.164.215.155!
ghost> 

please provide the solution.....just dont close it please .....please give the solution for the above error......if i put any ip address it always shows me the same error

**Comment by enty8080** [comment]
Try another IP, maybe invalid IP or IP is not vulnerable.
