### ISSUE TITLE
Failed to Start Ghost server after installation

### ISSUE THREAD

**Issue by Vivekanandg05** [entynetproject/ghost#109]
Failed to Start Ghost server after installation

**Comment by tamtonaquibjaved** [comment]
i too have the same problem.............................

**Comment by Hacker-allaround** [comment]
i have this tooo

**Comment by enty8080** [comment]
What OS do you use?

**Comment by anarayn** [comment]
I too have same problem. MacOS

**Comment by enty8080** [comment]
Because macOS does not have a pre-installed package manager, you should to install `brew` from https://brew.sh and execute `brew install adb`

**Comment by jackcrowfard** [comment]
Failed to start ghost server in kali linux

**Comment by whitehauler** [comment]
> Failed to start ghost server in kali linux

chmod +x install.sh

then,run ghost after that

**Comment by anonjokerps15** [comment]
failed start server after install in kali linux !!!what the issue here

**Comment by anonjokerps15** [comment]
> > Failed to start ghost server in kali linux
> 
> chmod +x install.sh
> 
> then,run ghost after that

dosent work bro !

**Comment by enty8080** [comment]
```
chmod +x install.sh
./install.sh
ghost
```

**Comment by enty8080** [comment]
**ALSO: Check if all default kali repos installed**

**Comment by Vivekanandg05** [comment]
Failed to start Ghost Server! in Kali linux  , could you please help to resolve this issue .

Steps Followed :
cd ghost
chmod +x install.sh
./install.sh
ghost

Failed to start Ghost Server!

**Comment by anonjokerps15** [comment]
> **ALSO: Check if all default kali repos installed**



> Failed to start Ghost Server! in Kali linux , could you please help to resolve this issue .
> 
> Steps Followed :
> cd ghost
> chmod +x install.sh
> ./install.sh
> ghost
> 
> Failed to start Ghost Server!

i also have same prob bro ! i did all that steps dosent help :3

**Comment by enty8080** [comment]
Type `apt-get update`, send output

**Comment by pavan555** [comment]
same here on macOS Catalina

**Comment by game-lover** [comment]
Do you run script as root?

**Comment by Vivekanandg05** [comment]
@enty8080 , here is the output

![image](https://user-images.githubusercontent.com/48043659/82899405-8e450000-9f78-11ea-959c-3244b4376b91.png)

**Comment by enty8080** [comment]
Maybe there is no adb in this repository. Try executing `apt install adb` and show output

**Comment by eliott23** [comment]
> Maybe there is no adb in this repository. Try executing `apt install adb` and show output
unable to locate packege adb

**Comment by chimadaking** [comment]
@Vivekanandg05 git clone https://github.com/mustaphaasbbar/android-tools-adb
install and run your ghost
