### ISSUE TITLE
Installation failed!

### ISSUE THREAD

**Issue by albert222222** [entynetproject/ghost#114]
It is showing that install.sh is not found.

**Comment by game-lover** [comment]
Can you add a screenshot of your problem?

**Comment by enty8080** [comment]
hey, @game-lover , this is a part that returns an error:
```shell
if [[ -d ~/ghost ]]
then
sleep 0
else
cd ~
{
git clone https://github.com/entynetproject/ghost.git
} &> /dev/null
fi

if [[ -d ~/ghost ]]
then
cd ~/ghost
else
echo -e ""$E"Installation failed!"
exit
fi
```

**Comment by enty8080** [comment]
**1.** Check Ghost Framework container, if exists, skip, if not execute `git clone <url_to_container>`

**2.** Check if clonned or not.

**Simple.**

**Comment by enty8080** [comment]
That means that @albert222222 have no git installed.

**Comment by enty8080** [comment]
Read install.sh, it installs git automatically via `apt-get, apt, eopkg, pkg, apk ...` and other package managers. @albert222222 What is your OS and package manager?

**Comment by albert222222** [comment]
![Screenshot_2020-05-25_16-42-17](https://user-images.githubusercontent.com/65748737/82873261-15e32e00-9ee9-11ea-8e87-b09cd273df9c.png)

**Comment by albert222222** [comment]
my os is kali linux

**Comment by albert222222** [comment]
![Screenshot_2020-05-26_10-54-42](https://user-images.githubusercontent.com/65748737/82875193-f1d51c00-9eeb-11ea-84a7-92e56908ee0b.png)

**Comment by albert222222** [comment]
Since, chmod does'nt  work ,I used "sudo  sh  install.sh" command to run it  as a root.
Is there any problem in that?

**Comment by game-lover** [comment]
Try this command
chmod +x install.sh
sudo ./install.sh

Or this command
 sudo . install.sh

**Comment by albert222222** [comment]
thank you@game -lover
It worked

**Comment by albert222222** [comment]
But what is the difference between previous code and 
chmod +x install.sh
sudo ./install.sh

Or this command
sudo . install.sh

**Comment by albert222222** [comment]
But why this command did'nt work
chmod +x install.sh
./install.sh

**Comment by game-lover** [comment]
It doesn’t work because installl.sh need root user

**Comment by enty8080** [comment]
🤦‍♂️ ./, not sh because this is not sh script this is bash script
