### ISSUE TITLE
[IMPORTANT] Issue Rules

### ISSUE THREAD

**Issue by enty8080** [entynetproject/ghost#116]
**1.** Do not report issues like:

`Failed to connect!`

Because this **is not** a Ghost Framework issue, this is **Network**, **Shodan** (if you use shodan), **IPv4/IPv6** or **adb** issues.

**Comment by Hacker-allaround** [comment]
i use my own phone but it is not connecting

**Comment by enty8080** [comment]
@Hacker-allaround do you have adb enabled on your phone?

**Comment by Hacker-allaround** [comment]
yes

**Comment by game-lover** [comment]
You can use ISSUE_TEMPLATE.md

**Comment by enty8080** [comment]
Can you send me what happened in you type this is your terminal:
`adb connect <your_ip>`

**Comment by game-lover** [comment]
You can use ISSUE TEMPLATE.md to set rules for issues

**Comment by tarkudroid** [comment]
If i write adb connect (mi ip) the terminal says: unable to connect (ip): Connection refused

**Comment by enty8080** [comment]
That means that your phone is not vulnerable. Congratulations
