### ISSUE TITLE
failed to start ghost server

### ISSUE THREAD

**Issue by ronnie8789** [entynetproject/ghost#121]
tried all the possibilities from all the other threads and issues but still cant find a way through.. I kindly request the developer to help me get out of the certain problem.. I'm leaving a screenshot for reference kindly help me. Thanks regards-

![Screenshot 2020-06-04 19:27:50](https://user-images.githubusercontent.com/66421958/83766113-9ea45b80-a699-11ea-9ff5-5ad9b516f51f.png)

**Comment by enty8080** [comment]
Thank you for reporting this error. Please try `apt-get install android-platform-tools`

**Comment by enty8080** [comment]
@ronnie8789 Try also `apt-get -y install android-tools-adb`

**Comment by ronnie8789** [comment]
> Thank you for reporting this error. Please try `apt-get install android-platform-tools`

When trying this it shows "E:unable to locate package android-platform-tools"

**Comment by enty8080** [comment]
> @ronnie8789 Try also `apt-get -y install android-tools-adb`

Try this too

**Comment by ronnie8789** [comment]
> @ronnie8789 Try also `apt-get -y install android-tools-adb`

tried this but found the same output "E:unable to locate package android-tools-adb"

**Comment by enty8080** [comment]
Do you have any repos installed on your computer?
Try `apt-get update` and show me output.

**Comment by ronnie8789** [comment]
but searched youtube a bit and found adb file was missing from my linux and then took help from a video and downloaded it by changing the sources.list file with some links from "https://www.kali.org/docs/general-use/kali-linux-sources-list-repositories/" and finally updating it...issue resolved! thank you sooo much @developer for responding so quickly and efficiently..thank you soo much mann may god bless you

**Comment by ronnie8789** [comment]
thank you mannn....
