### ISSUE TITLE
connection error

### ISSUE THREAD

**Issue by vaniaamad** [entynetproject/ghost#122]
very interesting tool unfortunately  it is not working , it wont connect to any phone ,any IP given to connect to. i have installed all the dependencies & everything but why inst it connecting?
can the developer plz help..
attached is the snap
![Screenshot 2020-06-05 04:19:37](https://user-images.githubusercontent.com/64696629/83819741-1c8d5480-a6e4-11ea-8839-c5cb3a5f1c95.png)

**Comment by enty8080** [comment]
Do you have adb enabled on your phone?

**Comment by vaniaamad** [comment]
dont know as i m trying this on a target phone...so whats the point of this tool if the adb is disbaled it wont work ? i thought this tool is to hack ? is there a way to enable adb on target phone?

**Comment by enty8080** [comment]
This tool is an adb automatization. A lot of the phones over the world have adb enabled and on shodan this named vulnerability. View:
https://www.shodan.io/search?query=Android+Debug+Bridge
