### ISSUE TITLE
Failed to start Ghost Server!

### ISSUE THREAD

**Issue by kamhawy4** [entynetproject/ghost#126]
i'm using ubuntu 18
when run : `sudo ghost`  An error appears : Failed to start Ghost Server!

**Comment by rakeshkali2020** [comment]
i,m using Kali 2020.2
when run: sudo ghost an error appears : failed to start Ghost Server. 
Couldn't sort out the problem.
I have also attached a screenshot of the error.
![Screenshot at 2020-06-08 05-01-06](https://user-images.githubusercontent.com/66587834/83999177-103d0d80-a917-11ea-8897-41787eb6b966.png)

**Comment by enty8080** [comment]
@kamhawy4 @rakeshkali2020 Execute `apt-get update` and send me output

**Comment by kamhawy4** [comment]
@enty8080 output

![Screenshot from 2020-06-08 16-12-11](https://user-images.githubusercontent.com/25951080/84040518-019c3800-a9a3-11ea-9ff9-3a5b1f2dfdbd.png)

**Comment by rakeshkali2020** [comment]
@enty8080 

![Screenshot at 2020-06-08 13-40-13](https://user-images.githubusercontent.com/66587834/84046925-911ff780-a95f-11ea-8271-4b5ec86b0d71.png)

**Comment by enty8080** [comment]
@kamhawy4 @rakeshkali2020 thanks, now execute `apt install android-platform-tools`

**Comment by enty8080** [comment]
And execute `adb`

**Comment by rakeshkali2020** [comment]
Thank you so much for the help. I re-cloned the framework and got it running perfectly but I still can't connect my phone with the command. I have updated it as well and also attached the screenshot.

It says 'Failed to connect <ip address>!.

![Screenshot at 2020-06-08 16-22-44](https://user-images.githubusercontent.com/66587834/84063644-33e37080-a976-11ea-8dde-33f65e3e06ef.png)

**Comment by enty8080** [comment]
Congratulations, your phone is not vulnerable! I created something like android VM, you can test Ghost Framework on this IP:
`125.78.217.234`

**Comment by kamhawy4** [comment]
no thanks  ^_^  :   when run  `apt install android-platform-tools`

this is output and The same problem exists

![Screenshot from 2020-06-08 22-41-23](https://user-images.githubusercontent.com/25951080/84078447-388d4080-a9d9-11ea-9884-12370b94525e.png)

**Comment by KENOSEC** [comment]
![Screenshot 2020-06-08 16:35:02](https://user-images.githubusercontent.com/66645654/84079034-dc5df880-a9a7-11ea-9fe1-707b07a0b1b4.png)
some one help ):

**Comment by rakeshkali2020** [comment]
@KENOSEC 
I think you should begin command with: sudo <directory name>

> ![Screenshot 2020-06-08 16:35:02](https://user-images.githubusercontent.com/66645654/84079034-dc5df880-a9a7-11ea-9fe1-707b07a0b1b4.png)
> some one help ):

**Comment by KENOSEC** [comment]
@rakeshkali2020 dosn't work same thing

**Comment by rakeshkali2020** [comment]
@

> no thanks ^_^ : when run `apt install android-platform-tools`
> 
> this is output and The same problem exists
> 
> ![Screenshot from 2020-06-08 22-41-23](https://user-images.githubusercontent.com/25951080/84078447-388d4080-a9d9-11ea-9884-12370b94525e.png)

> no thanks ^_^ : when run `apt install android-platform-tools`
> 
> this is output and The same problem exists
> 
> ![Screenshot from 2020-06-08 22-41-23](https://user-images.githubusercontent.com/25951080/84078447-388d4080-a9d9-11ea-9884-12370b94525e.png)

@kamhawy4 @enty8080 
At first, make sure you uninstall the ghost directory entirely and again re-clone the ghost framework from github. Thirdly, stay as a root user while installing ghost. Then finally use the command directed by the @enty8080 . I believe this should work because I have gone through these steps.

Last but not least. Be sure to checkout his (@enty8080) credentials before saying anything negative.
Atleast the guy is trying to help us. So be humble about it.

**Comment by KENOSEC** [comment]
@rakeshkali2020 why this ? 
![Screenshot 2020-06-08 17:11:31](https://user-images.githubusercontent.com/66645654/84080987-1f6d9b00-a9ab-11ea-86ce-374d9ef56d4b.png)

**Comment by rakeshkali2020** [comment]
> @rakeshkali2020 why this ?
> ![Screenshot 2020-06-08 17:11:31](https://user-images.githubusercontent.com/66645654/84080987-1f6d9b00-a9ab-11ea-86ce-374d9ef56d4b.png)
Send me the full screenshot not the cropped one

**Comment by kamhawy4** [comment]
> @
> 
> > no thanks ^_^ : when run `apt install android-platform-tools`
> > this is output and The same problem exists
> > ![Screenshot from 2020-06-08 22-41-23](https://user-images.githubusercontent.com/25951080/84078447-388d4080-a9d9-11ea-9884-12370b94525e.png)
> 
> > no thanks ^_^ : when run `apt install android-platform-tools`
> > this is output and The same problem exists
> > ![Screenshot from 2020-06-08 22-41-23](https://user-images.githubusercontent.com/25951080/84078447-388d4080-a9d9-11ea-9884-12370b94525e.png)
> 
> @kamhawy4 @enty8080
> At first, make sure you uninstall the ghost directory entirely and again re-clone the ghost framework from github. Thirdly, stay as a root user while installing ghost. Then finally use the command directed by the @enty8080 . I believe this should work because I have gone through these steps.
> 
> Last but not least. Be sure to checkout his (@enty8080) credentials before saying anything negative.
> Atleast the guy is trying to help us. So be humble about it.

 i'm sorry I didn't mean any negative words 
i am weak in English Language i'm sorry again  ^_^
 and Thank you for helping me @enty8080 @rakeshkali2020

**Comment by rakeshkali2020** [comment]
> > @
> > > no thanks ^_^ : when run `apt install android-platform-tools`
> > > this is output and The same problem exists
> > > ![Screenshot from 2020-06-08 22-41-23](https://user-images.githubusercontent.com/25951080/84078447-388d4080-a9d9-11ea-9884-12370b94525e.png)
> > 
> > 
> > > no thanks ^_^ : when run `apt install android-platform-tools`
> > > this is output and The same problem exists
> > > ![Screenshot from 2020-06-08 22-41-23](https://user-images.githubusercontent.com/25951080/84078447-388d4080-a9d9-11ea-9884-12370b94525e.png)
> > 
> > 
> > @kamhawy4 @enty8080
> > At first, make sure you uninstall the ghost directory entirely and again re-clone the ghost framework from github. Thirdly, stay as a root user while installing ghost. Then finally use the command directed by the @enty8080 . I believe this should work because I have gone through these steps.
> > Last but not least. Be sure to checkout his (@enty8080) credentials before saying anything negative.
> > Atleast the guy is trying to help us. So be humble about it.
> 
> i'm sorry I didn't mean any negative words
> i am weak in English Language i'm sorry again ^_^
> and Thank you for helping me @enty8080 @rakeshkali2020

So you're done. Is ghost running smoothly?

**Comment by kamhawy4** [comment]
> > > @
> > > > no thanks ^_^ : when run `apt install android-platform-tools`
> > > > this is output and The same problem exists
> > > > ![Screenshot from 2020-06-08 22-41-23](https://user-images.githubusercontent.com/25951080/84078447-388d4080-a9d9-11ea-9884-12370b94525e.png)
> > > 
> > > 
> > > > no thanks ^_^ : when run `apt install android-platform-tools`
> > > > this is output and The same problem exists
> > > > ![Screenshot from 2020-06-08 22-41-23](https://user-images.githubusercontent.com/25951080/84078447-388d4080-a9d9-11ea-9884-12370b94525e.png)
> > > 
> > > 
> > > @kamhawy4 @enty8080
> > > At first, make sure you uninstall the ghost directory entirely and again re-clone the ghost framework from github. Thirdly, stay as a root user while installing ghost. Then finally use the command directed by the @enty8080 . I believe this should work because I have gone through these steps.
> > > Last but not least. Be sure to checkout his (@enty8080) credentials before saying anything negative.
> > > Atleast the guy is trying to help us. So be humble about it.
> > 
> > 
> > i'm sorry I didn't mean any negative words
> > i am weak in English Language i'm sorry again ^_^
> > and Thank you for helping me @enty8080 @rakeshkali2020
> 
> So you're done. Is ghost running smoothly?

No . same problem

**Comment by enty8080** [comment]
@kamhawy4 Maybe something wrong with apt-get repositories, maybe there is no adb package in your default repositories, try searching for adb ported on your OS on the Internet.

**Comment by sirsoofaa** [comment]
> You are welcome ^_^ : when run `apt install android-platform-tools`
> 
> this is output and The same problem exists
> 
> ![Screenshot from 2020-06-08 22-41-23](https://user-images.githubusercontent.com/25951080/84078447-388d4080-a9d9-11ea-9884-12370b94525e.png)

**Hello**

All you need to do, Just run >> `sudo apt-get install android-tools-adb`

After you finish try to run `ghost` and **booom** 

**Cheers**

**Comment by SourabhKundu** [comment]
facing problem in starting ghost server in ghost framework. I have reinstalled it few times but i am facing same problem
![Screenshot from 2020-06-09 21-37-07](https://user-images.githubusercontent.com/38473810/84172379-8f2e6500-aa41-11ea-88b9-e4b4db7a4a6d.png)

**Comment by sirsoofaa** [comment]
> facing problem in starting ghost server in ghost framework. I have reinstalled it few times but i am facing same problem
> ![Screenshot from 2020-06-09 21-37-07](https://user-images.githubusercontent.com/38473810/84172379-8f2e6500-aa41-11ea-88b9-e4b4db7a4a6d.png)

All you need to do, Just run >> `sudo apt-get install android-tools-adb`

**Comment by SourabhKundu** [comment]
> > facing problem in starting ghost server in ghost framework. I have reinstalled it few times but i am facing same problem
> > ![Screenshot from 2020-06-09 21-37-07](https://user-images.githubusercontent.com/38473810/84172379-8f2e6500-aa41-11ea-88b9-e4b4db7a4a6d.png)
> 
> All you need to do, Just run >> `sudo apt-get install android-tools-adb`

I have tried this command also but package not found
![Screenshot from 2020-06-09 21-54-33](https://user-images.githubusercontent.com/38473810/84174228-f4835580-aa43-11ea-9216-77a1256c221b.png)

**Comment by enty8080** [comment]
@SourabhKundu Maybe something wrong with apt-get repositories, maybe there is no adb package in your default repositories, try searching for adb ported on your OS on the Internet.

**Comment by sirsoofaa** [comment]
> sudo apt-get install android-tools-adb

Please try the following :

`sudo add-apt-repository universe && sudo apt-get update && android-tools-fastboot`

and then use:

`sudo apt-get install android-tools-adb`

**Comment by neetu4444** [comment]
hey enty8080 i am getting an error,failed to connect a ghost server,ive followed all the steps correctly ,i use an. mac os system would you help me with it 
.

**Comment by neetu4444** [comment]
what to do with mac os ,im getting unable to start ghost frame work

**Comment by game-lover** [comment]
@kamhawy4

You can try to delete this ```deb https://brave-browser-apt-release.s3.brave.com bionic``` from etc/apt/sources.list and then run ```sudo apt-get update```

**Comment by snoopersur** [comment]
> > > > facing problem in starting ghost server in ghost framework. I have reinstalled it few times but i am facing same problem
> > > > ![Screenshot from 2020-06-09 21-37-07](https://user-images.githubusercontent.com/38473810/84172379-8f2e6500-aa41-11ea-88b9-e4b4db7a4a6d.png)
> > > 
> > > 
> > > All you need to do, Just run >> `sudo apt-get install android-tools-adb`
> > 
> > 
> > I have tried this command also but package not found
> > ![Screenshot from 2020-06-09 21-54-33](https://user-images.githubusercontent.com/38473810/84174228-f4835580-aa43-11ea-9216-77a1256c221b.png)
> 
> Please try the following :
> 
> `sudo add-apt-repository universe && sudo apt-get update && sudo apt-get install android-tools-adb android-tools-fastboot`
> 
> and then use:
> 
> `sudo apt-get install android-tools-adb`

it's really works.....try this doods.... thanks a lotzz....
#

**Comment by game-lover** [comment]
@enty8080 please add replace ./install.sh in your readme with sudo ./install.sh

**Comment by dwndnt** [comment]
can u help me plz? @enty8080 
I'm  got some error.
the ghost framework cannot connect to some IP addres.

or anyone can help to solve this problem?

**Comment by enty8080** [comment]
> @enty8080 please add replace ./install.sh in your readme with sudo ./install.sh

@game-lover 

No, if it runs install.sh without root it says ‘Permission denied!’ and user understands that he should run it as root. (logic) (Sorry for my English, I'm tired)

**Comment by snoopersur** [comment]
> can u help me plz? @enty8080
> I'm got some error.
> the ghost framework cannot connect to some IP addres.
> 
> or anyone can help to solve this problem?

Dear @enty8080 : We can't connect with All ip addresses.We Can only connect with some ip addresses which have the ADB (Android Debugging Bridge) Facility. Thank you!

**Comment by enty8080** [comment]
**DUBLICATE**: #112

**Comment by game-lover** [comment]
> > @enty8080 please add replace ./install.sh in your readme with sudo ./install.sh
> 
> @game-lover
> 
> No, if it runs install.sh without root it says ‘Permission denied!’ and user understands that he should run it as root. (logic) (Sorry for my English, I'm tired)

Some people don't understand what to do and opens issues

**Comment by khalidalwalid** [comment]
> @enty8080
> 
> Thank you so much for the help. I re-cloned the framework and got it running perfectly but I still can't connect my phone with the command. I have updated it as well and also attached the screenshot.
> 
> It says 'Failed to connect !.
> 
> ![Screenshot at 2020-06-08 16-22-44](https://user-images.githubusercontent.com/66587834/84063644-33e37080-a976-11ea-8dde-33f65e3e06ef.png)

I have the same problem in may kali 2020.2
Do you guys know how to fix this problem? Thanks

**Comment by game-lover** [comment]
Do you have adb enabled on your phone?

**Comment by khalidalwalid** [comment]
how do I check it?

**Comment by game-lover** [comment]
See this issue- [Issue 112](https://github.com/entynetproject/ghost/issues/112)

**Comment by khalidalwalid** [comment]
thx, I've just run ghost well with ip 113.255.243.54 from shodan.io
![Screenshot 2020-07-02 11:55:13](https://user-images.githubusercontent.com/33023197/86381149-fc0cd780-bc5a-11ea-8b6d-cc7b3d52326b.png)
