### ISSUE TITLE
Permission denied!

### ISSUE THREAD

**Issue by KENOSEC** [entynetproject/ghost#127]
![Screenshot 2020-06-08 16:35:02](https://user-images.githubusercontent.com/66645654/84078008-2ba32980-a9a6-11ea-89c1-d02b68eb2170.png)

**Comment by KENOSEC** [comment]
why this ?

**Comment by KENOSEC** [comment]
please help ):

**Comment by rakeshkali2020** [comment]
> please help ):

Let me see the complete screenshot for your screen with error not the cropped one or I can't help you anymore.

**Comment by enty8080** [comment]
@KENOSEC That means that your user have no permission to run this script, that means that you should to execute it as SUID. `sudo ./install.sh`.
