### ISSUE TITLE
> > > facing problem in starting ghost server in ghost framework. I have reinstalled it few times but i am facing same problem

### ISSUE THREAD

**Issue by SourabhKundu** [entynetproject/ghost#129]
> > > facing problem in starting ghost server in ghost framework. I have reinstalled it few times but i am facing same problem
> > > ![Screenshot from 2020-06-09 21-37-07](https://user-images.githubusercontent.com/38473810/84172379-8f2e6500-aa41-11ea-88b9-e4b4db7a4a6d.png)
> > 
> > 
> > All you need to do, Just run >> `sudo apt-get install android-tools-adb`
> 
> I have tried this command also but package not found
> ![Screenshot from 2020-06-09 21-54-33](https://user-images.githubusercontent.com/38473810/84174228-f4835580-aa43-11ea-9216-77a1256c221b.png)

Please try the following :

`sudo add-apt-repository universe && sudo apt-get update && sudo apt-get install android-tools-adb android-tools-fastboot`

and then use:

`sudo apt-get install android-tools-adb`

_Originally posted by @sirsoofaa in https://github.com/entynetproject/ghost/issues/126#issuecomment-641440634_

**Comment by SourabhKundu** [comment]
the above mentioned command is also not working and i am unable to upload screenshot.

**Comment by saurabhmadhu** [comment]
> @SourabhKundu Try `apt-get update && apt-get install android-tools`

This command not work can u plz help
