### ISSUE TITLE
Help with  Screenshot

### ISSUE THREAD

**Issue by Ph03n1x-Crus4d3** [entynetproject/ghost#13]
Whenever I take a screenshot, it does not save where I tell it to, even though the message says success. In fact, I cannot find where it saves at all. Any ideas?

**Comment by enty8080** [comment]
Is remote device rooted?

**Comment by enty8080** [comment]
Does remote device has root?

**Comment by enty8080** [comment]
Please send me your command

**Comment by enty8080** [comment]
Look here, my Android device is not rooted:
![screenn](https://user-images.githubusercontent.com/54115104/80273788-f5ebff00-86dd-11ea-9fea-ac1149f3a02e.png)

**Comment by enty8080** [comment]
Anything works fine...
