### ISSUE TITLE
Permission denied!

### ISSUE THREAD

**Issue by HanyZaher** [entynetproject/ghost#133]
I tried running this the framework on mac, termux, and ubuntu 20.04 with no luck what so ever.

```bash
me@my-computer ghost % chmod +x install.sh
```

```bash
me@my-computer ghost % ./install.sh
```

and I get this 

```bash
[-] Permission denied!
```

I hope I'm not missing anything here 

thanks in advance

**Comment by game-lover** [comment]
sudo ./install.sh

**Comment by HanyZaher** [comment]
thank you . . . worked
