### ISSUE TITLE
Failed to start Ghost Server!

### ISSUE THREAD

**Issue by VigneshSahoo** [entynetproject/ghost#14]
Hi,

I installed ghost as mentioned in the instructions. But when the try to start, it says Failed to start Ghost Server!.

root@kali:~/ghost# ghost
[-] Failed to start Ghost Server!

**Comment by Alpha-1729** [comment]
try python3 ghost

**Comment by anil9811** [comment]
root@kali:~/Desktop/ghost# python3 ghost
/usr/bin/python3: can't find '__main__' module in 'ghost'

Can you help us ? facing above error.

**Comment by VigneshSahoo** [comment]
@Alpha-1729 No use. Still getting same error.

root@kali:~/ghost# python3.8 ghost                                                                               
[-] Failed to start Ghost Server!

**Comment by anil9811** [comment]
@VigneshSahoo No use of it i think so ...Do you have any idea about any another framework to hack mobile phone remotely?

**Comment by anil9811** [comment]
Hi Guys 
I gone through the code of function startt server and i could able to see the below making me to get failed of ADB. can any one tell what is ADB

**Comment by VigneshSahoo** [comment]
@anil9811 Do we need ADB to run this? ADB is the Android Debug Bridge. I have it in my own machine. Not installed in the VM :-/. I thought dependencies will be installed automatically.

**Comment by anil9811** [comment]
yes i hope so but not sure if you open the ghost code i could able to see that

**Comment by anil9811** [comment]
try installing on the VM and check once  by running the ghost command .. please let me know the status as well

**Comment by ansariavaish** [comment]
sudo su
root@sudo ghost
Traceback (most recent call last):
  File "./ghost", line 27, in <module>
    import readline
ModuleNotFoundError: No module named 'readline'


can somebdy solve this error?

**Comment by darklord-666** [comment]
To start the ghost-server you have to start the adb server first..after starting the adb server my problem solved..

**Comment by enty8080** [comment]
Just execute installer
