### ISSUE TITLE
ghost installation freeze

### ISSUE THREAD

**Issue by daman1321** [entynetproject/ghost#140]
I tried to install ghost framework couple of time but it is having the same problem every time it got freeze after i executed the install command
<img width="896" alt="Screen Shot  AM" src="https://user-images.githubusercontent.com/61426060/86049263-7a0c8b00-ba6f-11ea-8a68-225464cd0f85.png">

**Comment by enty8080** [comment]
If your using old version of system, Ghost will update all packages. Because of this it takes long time to install it.
