### ISSUE TITLE
Failed to start Ghost Server!

### ISSUE THREAD

**Issue by khalidalwalid** [entynetproject/ghost#141]
After the installation's done, when I want to run ghost, it says "Failed to start Ghost Server!".
How do I solve it, then.
Thx.
![Screenshot 2020-07-02 04:29:20](https://user-images.githubusercontent.com/33023197/86335749-e8db1700-bc1c-11ea-9ef0-d6b7216f437a.png)

**Comment by khalidalwalid** [comment]
> After the installation's done, when I want to run ghost, it says "Failed to start Ghost Server!".
> How do I solve it, then?
> Thx.
> ![Screenshot 2020-07-02 04:29:20](https://user-images.githubusercontent.com/33023197/86335749-e8db1700-bc1c-11ea-9ef0-d6b7216f437a.png)

By the way, I'm using kali linux 2020.2

**Comment by game-lover** [comment]
[#126](https://github.com/entynetproject/ghost/issues/126)

**Comment by cyberfling** [comment]
I don't get beyond the 'installing dependences' screen. It always connects to github and after I log in, I get 'Installation failed' . My login details are correct but I keep geting the 'installation failed' response. What could be wrong and why do I have to log in with Github in the first place?

**Comment by thecakeisfalse** [comment]
@cyberfling can you send a screenshot of error?

**Comment by cyberfling** [comment]
Hi, thanks for reply. I have now solved it - used pip3 to install entysec version 8 (I believe) - now working. Once again, many thanks.
