### ISSUE TITLE
import readline

### ISSUE THREAD

**Issue by dhirajwanem** [entynetproject/ghost#145]
Traceback (most recent call last):
  File "./ghost", line 27, in <module>
    import readline
ModuleNotFoundError: No module named 'readline'

**Comment by game-lover** [comment]
pip3 install readline

**Comment by dhirajwanem** [comment]
free(): invalid pointer
Aborted

**Comment by game-lover** [comment]
try this command:
```bash
pip3 install gnureadline
```

**Comment by dhirajwanem** [comment]
Doesnot worked
free(): invalid pointer
/usr/local/bin/ghost: line 93:  3999 Aborted                 ./ghost

**Comment by enty8080** [comment]
@dhirajwanem OS?

**Comment by dhirajwanem** [comment]
kali linux

**Comment by enty8080** [comment]
Try `ls /usr/include/readline`.

**Comment by enty8080** [comment]
```
apt-get update
apt-get install libreadline-dev
```

**Comment by game-lover** [comment]
Try this

```bash
sudo apt-get install libbz2-dev libncurses5-dev libgdbm-dev liblzma-dev sqlite3 libsqlite3-dev openssl libssl-dev tcl8.6-dev tk8.6-dev libreadline-dev zlib1g-dev
```

**Comment by game-lover** [comment]
```bash
pip3 uninstall readline
pip3 install gnureadline
```

**Comment by enty8080** [comment]
Promblem not in python3 library. This is a readline.h error.

**Comment by dhirajwanem** [comment]
then how to fix it please help me

**Comment by game-lover** [comment]
What have you tried?

**Comment by enty8080** [comment]
`apt-get install libreadline-dev`

**Comment by game-lover** [comment]
If you think that it is readline error, you can build readline from source

**Comment by enty8080** [comment]
Just install `libreadline-dev` via `apt-get`

**Comment by dhirajwanem** [comment]
yes but it didnt worked

**Comment by dhirajwanem** [comment]
please help me to solve this eror

**Comment by game-lover** [comment]
pip3 uninstall readline
pip3 install gnureadline

**Comment by dhirajwanem** [comment]
it worked thanks uh very  very very much for helping me

**Comment by game-lover** [comment]
What have you tried?

**Comment by dhirajwanem** [comment]
can we communicate eachother
plz add me on facebook or any other site

**Comment by dhirajwanem** [comment]
i tried 
pip3 uninstall readline
pip3 install gnureadline

**Comment by game-lover** [comment]
follow @game-lover

**Comment by dhirajwanem** [comment]
oky but where in instagram or?

**Comment by game-lover** [comment]
do you have twitter?

**Comment by dhirajwanem** [comment]
i dont have
do you have facebook

**Comment by game-lover** [comment]
nope, can you follow me on github?

**Comment by dhirajwanem** [comment]
oky bro i will

**Comment by dhirajwanem** [comment]
[-] Failed to connect to 27.34.51.24!

**Comment by game-lover** [comment]
[#112](https://github.com/entynetproject/ghost/issues/112)

**Comment by dhirajwanem** [comment]
what is the reason of this error bro
[-] Failed to connect to 27.34.51.24!

**Comment by game-lover** [comment]
this is common issue. can you try another IP address?

**Comment by dhirajwanem** [comment]
oky bro

**Comment by game-lover** [comment]
why do you call me bro?

**Comment by dhirajwanem** [comment]
sorry i didnt know your name so anyway what is your name

**Comment by game-lover** [comment]
Simon

**Comment by dhirajwanem** [comment]
oky simon do you know facebook hacking

**Comment by game-lover** [comment]
why are you asking?

**Comment by dhirajwanem** [comment]
i want to know thats why

**Comment by dhirajwanem** [comment]
plz bro tech me

**Comment by game-lover** [comment]
ask @enty8080

**Comment by dhirajwanem** [comment]
sh: 0: getcwd() failed: No such file or directory
chmod: cannot access 'core/dctl.sh': No such file or directory
sh: 0: getcwd() failed: No such file or directory
sh: 0: getcwd() failed: No such file or directory
[-] Failed to connect to 27.34.51.24!
sh: 0: getcwd() failed: No such file or directory
chmod: cannot access 'core/dctl.sh': No such file or directory

**Comment by game-lover** [comment]
what have you done?

**Comment by dhirajwanem** [comment]
i tried to connect with that ip adress

**Comment by game-lover** [comment]
reinstall

**Comment by dhirajwanem** [comment]
if same problem ocurs then

**Comment by game-lover** [comment]
reinstall ghost

**Comment by dhirajwanem** [comment]
i have reinstalled but it doesnot worked bro

**Comment by game-lover** [comment]
show output

**Comment by enty8080** [comment]
I use kali linux, for me everything works correctly

**Comment by dhirajwanem** [comment]
same output bro

**Comment by dhirajwanem** [comment]
failed to connect

**Comment by dhirajwanem** [comment]
game-lover help me unabe to connect to ip

**Comment by game-lover** [comment]
[#112](https://github.com/entynetproject/ghost/issues/112)
