### ISSUE TITLE
failed to connect ip adress

### ISSUE THREAD

**Issue by dhirajwanem** [entynetproject/ghost#147]
plz help me

**Comment by dhirajwanem** [comment]
failed to connect ip adress

**Comment by enty8080** [comment]
#104

**Comment by enty8080** [comment]
#112

**Comment by dhirajwanem** [comment]
please send me solutions bro

**Comment by dhirajwanem** [comment]
be serious man it has became completely useless because it disconnects with every type of ip

**Comment by game-lover** [comment]
what type of IPs do you use?
