### ISSUE TITLE
failed to connect server

### ISSUE THREAD

**Issue by joe-samoita** [entynetproject/ghost#149]

**Comment by joe-samoita** [comment]
i installed ghost and its says failed to start ghost server how can io fix it?

**Comment by Syedbadshah123** [comment]
i install ghost and when i type ./install.sh it says permission denied
why????

**Comment by game-lover** [comment]
sudo ./install.sh

**Comment by game-lover** [comment]
@joe-samoita do you run ghost on virtual machine?

**Comment by game-lover** [comment]
@joe-samoita what os do you use?

**Comment by joe-samoita** [comment]
Nop on linux os
Anyway i did fix the problem but when i try to connect to any ip address it
says  /bin/s: 1: adb not found
How can i fix that pls

On 23 Jul 2020 12:39 p.m., "Simon Chaykin" <notifications@github.com> wrote:

@joe-samoita <https://github.com/joe-samoita> do you run ghost on virtual
machine?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/entynetproject/ghost/issues/149#issuecomment-662913039>,
or unsubscribe

**Comment by game-lover** [comment]
What linux distro do you use?

**Comment by joe-samoita** [comment]
Debian

**Comment by game-lover** [comment]
sudo apt-get install android-tools-adb android-tools-fastboot

**Comment by game-lover** [comment]
> i install ghost and when i type ./install.sh it says permission denied
> 
> why????
> 
> 

@Syedbadshah123 sudo ./install.sh

**Comment by joe-samoita** [comment]
Package not found it says

**Comment by game-lover** [comment]
@joe-samoita what package?

**Comment by enty8080** [comment]
try the following commands, one of them should works:
```
apt-get update
apt-get install android-adb
apt-get install adb
apt-get install android-tools-adb
apt-get install android-tools
```

**Comment by AdhamNader** [comment]
I have a problem connecting to the target device everytime i connect it says  `failed to connect to the 00.000.000.00`
And btw the 0s are the ip address an example!!!

**Comment by enty8080** [comment]
#112
