### ISSUE TITLE
Failed to Start ghost Server

### ISSUE THREAD

**Issue by vipuluthaiah** [entynetproject/ghost#15]
When i run sudo ghost its giving an error 
Failed to start ghost server!

**Comment by Za3fraNaa** [comment]
When i run sudo ghost its giving an error
Failed to start ghost server

**Comment by darklord-666** [comment]
https://github.com/entynetproject/ghost/issues/14#issuecomment-622340760

**Comment by darklord-666** [comment]
> When i run sudo ghost its giving an error
> Failed to start ghost server!



> When i run sudo ghost its giving an error
> Failed to start ghost server!

Start the adb server first and then type sudo ghost

**Comment by enty8080** [comment]
Just reinstall adb in PATH
