### ISSUE TITLE
Error relocating while connecting

### ISSUE THREAD

**Issue by AliVeliyev** [entynetproject/ghost#151]
**There is the error which I got**

Error relocating /usr/bin/adb: __gmtime64_r: symbol not found
Error relocating /usr/bin/adb: __stat_time64: symbol not found
Error relocating /usr/bin/adb: __localtime64_r: symbol not found
Error relocating /usr/bin/adb: __lstat_time64: symbol not found
Error relocating /usr/bin/adb: __time64: symbol not found
Error relocating /usr/bin/adb: __pthread_cond_timedwait_time64: symbol not found
Error relocating /usr/bin/adb: __utime64: symbol not found
Error relocating /usr/bin/adb: __fstat_time64: symbol not found
Error relocating /usr/bin/adb: __nanosleep_time64: symbol not found
Error relocating /usr/bin/adb: __select_time64: symbol not found
Error relocating /usr/bin/adb: __gmtime64_r: symbol not found
Error relocating /usr/bin/adb: __stat_time64: symbol not found
Error relocating /usr/bin/adb: __localtime64_r: symbol not found
Error relocating /usr/bin/adb: __lstat_time64: symbol not found
Error relocating /usr/bin/adb: __time64: symbol not found
Error relocating /usr/bin/adb: __pthread_cond_timedwait_time64: symbol not found
Error relocating /usr/bin/adb: __utime64: symbol not found
Error relocating /usr/bin/adb: __fstat_time64: symbol not found
Error relocating /usr/bin/adb: __nanosleep_time64: symbol not found
Error relocating /usr/bin/adb: __select_time64: symbol not found
[-] Failed to connect to 37.26.27.129!

**Comment by game-lover** [comment]
WOW! It's really cool

**Comment by game-lover** [comment]
@AliVeliyev what os do you use?

**Comment by AliVeliyev** [comment]
Alpine linux

**Comment by game-lover** [comment]
@AliVeliyev how did you install adb?

**Comment by AliVeliyev** [comment]
using this link: apk --update-cache --repository http://dl-3.alpinelinux.org/alpine/edge/testing/ add android-tools

**Comment by enty8080** [comment]
Contact alpine tech group. This problem is not in Ghost, this is an adb error. Or I can just say that Alpine Linux does not supported by Ghost Framework.

**Comment by game-lover** [comment]
> Contact alpine tech group. This problem is not in Ghost, this is an adb error. Or I can just say that Alpine Linux does not supported by Ghost Framework.

Don't be stupid
