### ISSUE TITLE
Error while connecting to a host.

### ISSUE THREAD

**Issue by Nithish-maker** [entynetproject/ghost#154]
**This is the error while i was trying to connect to a ip..**

sh: 0: getcwd() failed: No such file or directory
chmod: cannot access 'core/dctl.sh': No such file or directory
sh: 0: getcwd() failed: No such file or directory
sh: 0: getcwd() failed: No such file or directory
[-] Failed to connect to 220.72.41.77!
sh: 0: getcwd() failed: No such file or directory
chmod: cannot access 'core/dctl.sh': No such file or directory

I have also installed the adb on my platform and the command sending the payload to the given ip is not showing and immediately it gets failed to connect and not able to send the payload..
So please help me with this issue..

**Comment by enty8080** [comment]
#112
