### ISSUE TITLE
android-tools package does not exist

### ISSUE THREAD

**Issue by peebowo** [entynetproject/ghost#156]
android-tools package cannot be located.

root@localhost:~# apt install android-tools       Reading package lists... Done
Building dependency tree                          Reading state information... Done                 E: Unable to locate package android-tools

**Comment by L3KTRO** [comment]
same

**Comment by game-lover** [comment]
sudo apt install android-tools-adb

**Comment by peebowo** [comment]
> sudo apt install android-tools-adb
Reading package lists... Done 
Building dependency tree... Done 
E: Unable to locate package android-tools-adb
$

**Comment by enty8080** [comment]
idk

**Comment by game-lover** [comment]
What distro do you use?

**Comment by PSNAppz** [comment]
Try this:

https://askubuntu.com/questions/923485/trying-to-install-android-tools-adb-and-getting-unable-to-locate-package
