### ISSUE TITLE
unrecognised command

### ISSUE THREAD

**Issue by kattasainaveen** [entynetproject/ghost#158]
ghost> update
[-] Unrecognized command!
ghost> connect 39.155.194.181
[-] Unrecognized command!

Please help

**Comment by sanjaysratuuri** [comment]
Kindly exit by pressing control C and again start Ghost and it will work fine

**Comment by kattasainaveen** [comment]
Please help,

host> connect 39.155.194.181
[*] Connecting to 39.155.194.181...
[-] Failed to connect to 39.155.194.181!

**Comment by game-lover** [comment]
[#112](https://github.com/entynetproject/ghost/issues/112)
