### ISSUE TITLE
Ghost Info

### ISSUE THREAD

**Issue by sanjaysratuuri** [entynetproject/ghost#159]
Excellent it works. I just have one question i.e does it only works on rooted device or it works on un rooted device also
As when I tried to connect it to my personal mobile (which is not rooted) it is giving following error:
ghost> connect <my ip>
[*] Connecting to <my ip>...
[-] Failed to connect to <my ip>!

is it due to my phone is not rooted.

**Comment by GGorAA** [comment]
Also have this issue. I was trying to connect to my personal phone, and it also gave me an error. What can we do to fix it?

**Comment by game-lover** [comment]
[#112](https://github.com/entynetproject/ghost/issues/112)

**Comment by enty8080** [comment]
@GGorAA @sanjaysratuuri You should have adb enabled on your device.
