### ISSUE TITLE
server failed

### ISSUE THREAD

**Issue by rajthedeveloper101** [entynetproject/ghost#160]
sudo ghost
[-] Failed to start Ghost Server!

**Comment by game-lover** [comment]
try without sudo

**Comment by rajthedeveloper101** [comment]
It not working Same error is reapting “UNABLE TO ESTABLISH SSL CONNECTION”  Sent from Mail for Windows 10 From: Simon ChaykinSent: 10 August 2020 03:50 PMTo: entynetproject/ghostCc: rajthedeveloper101; AuthorSubject: Re: [entynetproject/ghost] server failed (#160) try without sudo—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by game-lover** [comment]
Do you run it on virtual machine?

**Comment by rajthedeveloper101** [comment]
yess Sent from Mail for Windows 10 From: Simon ChaykinSent: 10 August 2020 04:56 PMTo: entynetproject/ghostCc: rajthedeveloper101; AuthorSubject: Re: [entynetproject/ghost] server failed (#160) Do you run it on virtual machine?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by enty8080** [comment]
install adb client

**Comment by rajthedeveloper101** [comment]
How can I Can u share any youtube link bro plz  Sent from Mail for Windows 10 From: Ivan NikolskySent: 10 August 2020 05:54 PMTo: entynetproject/ghostCc: rajthedeveloper101; AuthorSubject: Re: [entynetproject/ghost] server failed (#160) install adb client—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
