### ISSUE TITLE
Can't connect to a device

### ISSUE THREAD

**Issue by GGorAA** [entynetproject/ghost#161]
Hello,

I tried to connect to my personal phone running Android 9, phone is Galaxy J7 Pro. I scanned its IP address for open ports, and 5555 port(adb port, actually) is open. I tried to connect to it, but connection fails all the times. I wrote: `connect <ip>`, and then it returned me an error saying `Failed to connect to <ip>!`. How to gif this issue? Do I need to wait for 6.0 release?

**Comment by enty8080** [comment]
#112
