### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by vlakhani28** [entynetproject/ghost#166]
I tried to install ghost using the following commands
chmod +x install.sh
./install.sh

It states downloading dependencies and then says Downloading Failed although my internet connection is perfect.

Pls help
![Screenshot (38)](https://user-images.githubusercontent.com/42069316/91144990-69c10700-e6d2-11ea-843d-fbe460c1332d.png)

**Comment by game-lover** [comment]
You cannot use ghost on virtual machine

**Comment by game-lover** [comment]
Or try to delete
```bash
{
ASESR="$(ping -c 1 -q www.google.com >&/dev/null; echo $?)"
} &> /dev/null
if [[ "$ASESR" != 0 ]]
then 
   echo -e ""$E"No Internet connection!"
   exit
fi
```
from install.sh

**Comment by vlakhani28** [comment]
> You cannot use ghost on virtual machine

Ohh Just curious to know why is it show

**Comment by vlakhani28** [comment]
> Or try to delete
> 
> ```shell
> {
> ASESR="$(ping -c 1 -q www.google.com >&/dev/null; echo $?)"
> } &> /dev/null
> if [[ "$ASESR" != 0 ]]
> then 
>    echo -e ""$E"No Internet connection!"
>    exit
> fi
> ```
> 
> from install.sh

Nope this isnt working still showing same installation error

**Comment by game-lover** [comment]
Do you have git installed?

**Comment by vlakhani28** [comment]
> Do you have git installed?

Yes

**Comment by game-lover** [comment]
Please show me output of 
```bash
ls ~/ghost
```

**Comment by vlakhani28** [comment]
I hope i captured the right SS
![Screenshot (40)](https://user-images.githubusercontent.com/42069316/91209164-ec74b100-e728-11ea-9f4f-26d0b71be860.png)

**Comment by game-lover** [comment]
ls ~/ghost not ./ghost

**Comment by vlakhani28** [comment]
![Screenshot (41)](https://user-images.githubusercontent.com/42069316/91210457-e1bb1b80-e72a-11ea-9528-326cae5426f1.png)

**Comment by vlakhani28** [comment]
I did this the error is it isnt able to install dependencies

**Comment by vlakhani28** [comment]
Perfect this worked for me
 
Thank You for all the help!
![Screenshot (42)](https://user-images.githubusercontent.com/42069316/91212675-2b593580-e72e-11ea-9aa3-c8f288294ee4.png)

**Comment by game-lover** [comment]
follow @game-lover

**Comment by game-lover** [comment]
Can you close this issue?

**Comment by vlakhani28** [comment]
> follow @game-lover

Did that thanks
