### ISSUE TITLE
Unrecognized command (after closing and starting ghost again)

### ISSUE THREAD

**Issue by Morsmalleo** [entynetproject/ghost#167]
I have installed Ghost Framework successfully and I've had this "unrecognized command" error keep coming up when typing valid commands such as "clear" "exit" "connect" they all say "unrecognized command"

I seen in similar issue that if this "unrecognized command" error keeps happening, I can close Ghost Framework by pressing Ctrl + C, however the problem here is that I have closed and started Ghost Framework multiple times and the same error keeps happening, its not fixing my problem, I keep getting "unrecognized command" when typing valid commands even after closing and starting Ghost Framework again. 

Please help :)

**Comment by game-lover** [comment]
You need to go to line 449 and delete 4 spaces in ~/ghost/ghost

**Comment by game-lover** [comment]
You need to go to line 449 and delete 4 spaces in ~/ghost/etc/ghost

**Comment by enty8080** [comment]
@Morsmalleo @game-lover Sorry, this is a bug. Now fixed, reinstall
