### ISSUE TITLE
permition denained  unable to start ghost on my virtual kali

### ISSUE THREAD

**Issue by CHAMP6969** [entynetproject/ghost#168]

**Comment by game-lover** [comment]
sudo ./install.sh

**Comment by game-lover** [comment]
Unable to start ghost - [#86](https://github.com/entynetproject/ghost/issues/86)

**Comment by Bugillero** [comment]
tengo el mismo problema 
kali@kali:~$ git clone https://github.com/entynetproject/ghost.git
Cloning into 'ghost'...
fatal: unable to access 'https://github.com/entynetproject/ghost.git/': Could not resolve host: github.com

**Comment by game-lover** [comment]
You are not connected to the internet
