### ISSUE TITLE
Does it support android version under 10?

### ISSUE THREAD

**Issue by Hmlchy** [entynetproject/ghost#17]
Well, I have 3 devices as follows:

* Android 10
* Android 7
* Android 5

In the developer settings for android 10, there is an option for wireless debugging which is absent in the other two phones. 

And I could only connect to the android 10 device and others weren't connected ( which I assume was because they didn't have wireless ADB option)

So, this only works for devices running android 10?

**Comment by enty8080** [comment]
yes
