### ISSUE TITLE
ssh: Could not resolve hostname github.com

### ISSUE THREAD

**Issue by Bugillero** [entynetproject/ghost#172]
Cloning into 'ghost'...
ssh: Could not resolve hostname github.com: Temporary failure in name resolution
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by game-lover** [comment]
You are not connected to the internet

**Comment by Bugillero** [comment]
ya esta arreglado solo es ponerlo en conexion NAT
