### ISSUE TITLE
issue when installing 

### ISSUE THREAD

**Issue by sumitsaini326** [entynetproject/ghost#177]
$ ./install.sh
./install.sh: line 2: $'\r': command not found
./install.sh: line 4: $'\r': command not found
./install.sh: line 9: $'\r': command not found
./install.sh: line 10: syntax error in conditional expression
'/install.sh: line 10: syntax error near `]]
'/install.sh: line 10: `if [[ $(id -u) != 0 ]]

**Comment by Bhaviktutorials** [comment]
Are you using root account?

**Comment by sumitsaini326** [comment]
Yes. With virtual box ubantu.
Iam  trying Manny time but didn't work.

**Comment by enty8080** [comment]
Something wrong with your shell, reinstall bash and try again
