### ISSUE TITLE
Getting error while running ghost tool

### ISSUE THREAD

**Issue by Bhaviktutorials** [entynetproject/ghost#178]
I am using ghost tool in termux.
One month age the tool was working well in termux with root access but I don't know now what has happened it's showing me:-
[-] Failed to start Ghost Server!

Everything is installed perfectly no issues in installation. 
And termux is also In lasted version
I know this tool is not made for termux but first it was working perfectly now what happened idk
![Screenshot_20200915_155437](https://user-images.githubusercontent.com/64035221/93199789-759d6780-f76c-11ea-8b4f-41f03c50923a.jpg)

**Comment by enty8080** [comment]
Install `adb`
