### ISSUE TITLE
Failed to connect to

### ISSUE THREAD

**Issue by LogicatedDev** [entynetproject/ghost#186]
Whenever I enter the IP to connect to it says "Failed to connect to IP" how do I fix this? It's really annoying and I'm not sure what to do so I came here for help.

**Comment by enty8080** [comment]
#96

**Comment by enty8080** [comment]
And you need to adb enabled on your phone.

**Comment by raiden21211** [comment]
> And you need to adb enabled on your phone.

still not working man i would like to get help too..

**Comment by raiden21211** [comment]
trying to connect to my phone but it says : Failed to connect to xxx.xxx.xxx.xxx , but when i tried a random ip (took from a shodan screenshot) it connected, (adb enabled) does anyone know why?
