### ISSUE TITLE
No module named 'readline'

### ISSUE THREAD

**Issue by simo-bambou** [entynetproject/ghost#187]
root@kali:/home/kali/ghost# ghost
[*] Starting Ghost Framework
Traceback (most recent call last):
  File "./ghost", line 15, in <module>
    import readline
ModuleNotFoundError: No module named 'readline'

**Comment by game-lover** [comment]
pip3 install gnureadline

**Comment by romero01413** [comment]
$ ghost 
Traceback (most recent call last):
  File "/home/kali/.ghost/./ghost", line 33, in <module>
    import readline
ModuleNotFoundError: No module named 'readline'

**Comment by game-lover** [comment]
pip3 install gnureadline
