### ISSUE TITLE
NameError: name 'G' is not defined

### ISSUE THREAD

**Issue by uzzalhossain2020** [entynetproject/ghost#188]
Traceback (most recent call last):
  File "./ghost", line 553, in <module>
    main()
  File "./ghost", line 134, in main
    print(G+"Connecting to "+target+"...")
NameError: name 'G' is not defined

**Comment by S3Cd3d** [comment]
Im same issue.

**Comment by edu1234567890** [comment]
same issue

**Comment by Devilzeyez** [comment]
i have the same issue also

**Comment by enty8080** [comment]
@uzzalhossain2020 @edu1234567890 @Devilzeyez @S3Cd3d This fixed now, reinstall it

**Comment by Devilzeyez** [comment]
thanks for the update but can not connect to anything connection failed
