### ISSUE TITLE
No internet connection! 

### ISSUE THREAD

**Issue by jkx56** [entynetproject/ghost#22]
When i try to install ghost on ubuntu 20.04 i get the no internet connection, but not on my kali linux !

**Comment by enty8080** [comment]
Look:
```shell
{
ASESR="$( curl -s checkip.dyndns.org | sed -e 's/.*Current IP Address: //' -e 's/<.*$//' )"
} &> /dev/null
if [[ "$ASESR" = "" ]]
then 
   sleep 1
   echo -e ""$RS"[-] "$WHS"No Internet connection!"$CE""
   sleep 1
   exit
fi
```
This code is intended to check your internet connection, if there is no internet connection it types No Internet connection, but if you have the internet conection but with low speed, this code returns No Internet connection too.

**And remember that the Kali Linux is Debian, Ubuntu is a Debian too!**

**Comment by enty8080** [comment]
cURL has no default installation in Ubuntu, we will fix this soon
