### ISSUE TITLE
upload issue

### ISSUE THREAD

**Issue by c0-sudo** [entynetproject/ghost#24]
Hi, 

When I try to `upload` just a simple file.txt I have an error crashes ghost-framework : 

`ghost(XX.XXX.XXX.XX:5555)> upload Zone.txt Downloads
Traceback (most recent call last):
  File "./ghost", line 479, in <module>
    main()
  File "./ghost", line 460, in main
    rp = rp[rp.index('/')+1:][::-1]
ValueError: substring not found`

Dunno why is doing this...

OS used : MacOS Cataline 10.15.1 && Linux Kali 4.19.93-Re4son-V7 

Appreciate your help :)

**Comment by enty8080** [comment]
You should to define full remote path
