### ISSUE TITLE
error while trying to connect to ip

### ISSUE THREAD

**Issue by jilalitajdine** [entynetproject/ghost#25]
hi
when i try to connect i get this error

double free or corruption (out)
/usr/local/bin/ghost: line 85: 25311 Aborted

any fix please?

thank you

**Comment by enty8080** [comment]
OS?

**Comment by jilalitajdine** [comment]
> OS?

Parrot 4.8

sorry for delay. Thanks

**Comment by enty8080** [comment]
Please sent me screenshot of the error
