### ISSUE TITLE
unable to save screenrec to local 

### ISSUE THREAD

**Issue by ertanuj96** [entynetproject/ghost#27]
showing video has been saved to local folder but there is no mp4 file in destination directory

**Comment by heydrickanonymous-cyber** [comment]
there is same problem with me

**Comment by mailbagrahul** [comment]
Are you guys able to connect to the IP? because I'm unable to connect. it is failing.

**Comment by enty8080** [comment]
Sent me the command

**Comment by Loubaris** [comment]
Screenrec don't work, it's not saving the file
