### ISSUE TITLE
sudo ghost doesn't open ghost

### ISSUE THREAD

**Issue by lollypo** [entynetproject/ghost#28]
root@kali:~# sudo ghost
Traceback (most recent call last):
  File "./ghost", line 27, in <module>
    import readline
ModuleNotFoundError: No module named 'readline'

**Comment by jilalitajdine** [comment]
> root@kali:~# sudo ghost
> Traceback (most recent call last):
> File "./ghost", line 27, in
> import readline
> ModuleNotFoundError: No module named 'readline'

fix with 
pip install readline

**Comment by vikram1211** [comment]
sudo ghost
Traceback (most recent call last):
  File "./ghost", line 27, in <module>
    import readline
ModuleNotFoundError: No module named 'readline'
root@blackhat:~# pip install readline
bash: pip: command not found

**Comment by enty8080** [comment]
🤦‍♂️ **RTFM**

**Comment by Monticore-h** [comment]
root@kali:~# sudo ghost
Traceback (most recent call last):
File "./ghost", line 27, in
import readline
ModuleNotFoundError: No module named 'readline'
root@kali:~/ghost# pip install readline
Requirement already satisfied: readline in /usr/local/lib/python3.9/dist-packages (6.2.4.1)

After that its showing same error......
pls reply pls pls fix this

**Comment by Monticore-h** [comment]
i dunno why the line is there so pls ignore that line and give me the solution.[](url)
