### ISSUE TITLE
Having issues while saving screen shots and screen record

### ISSUE THREAD

**Issue by heydrickanonymous-cyber** [entynetproject/ghost#29]
[*] Recording screen...
[*] Press Ctrl-C to stop.
^C[*] Saving to /root/Desktop/screen.mp4...
[+] Saved to /root/Desktop/screen.mp4!
------------------------------------------------------------------------------
OS: Kali Linux 2019 rooted version
requirements are installed and updated daily on this machine.

**Comment by enty8080** [comment]
What the problem?
