### ISSUE TITLE
ghost start faillure !

### ISSUE THREAD

**Issue by MERMAIiD** [entynetproject/ghost#3]
.-.
    .'   `.
    :0 0  :
    : o    `.
   :         ``.
  :             `.
 :  :         .   `.
 :   :          ` . `.
  `.. :            `. ``;
     `:;             `:'
        :              `.
         `.              `.     
           `'`'`'`---..,___`.

Ghost Framework v5.0
--------------------

ghost> help
Traceback (most recent call last):
  File "./ghost", line 232, in <module>
    main()
  File "./ghost", line 86, in main
    elif con == "clear":
UnboundLocalError: local variable 'con' referenced before assignment

**Comment by enty8080** [comment]
Sorry, I’ll fix this now

**Comment by enty8080** [comment]
This is fixed! Can I close this issue?

**Comment by MERMAIiD** [comment]
re downloaded and installed again. still the same error!

**Comment by enty8080** [comment]
This is very strange because I fix this))
