### ISSUE TITLE
unable to Connect Ip

### ISSUE THREAD

**Issue by faraz911** [entynetproject/ghost#30]
For example if my android Ip is 192.168.0.140 and used port 5555 but failed process what i can do? how i can fix this issue to remotely access my testing device

**Comment by mailbagrahul** [comment]
Same here. Unable to connect to the IP address. Please assist.

**Comment by enty8080** [comment]
`ghost> connect <ip>`
**Without port**
**Enable android debug bridge**

**Comment by faraz911** [comment]
How i can enable android debug bridge
