### ISSUE TITLE
No internet connection !

### ISSUE THREAD

**Issue by J01010** [entynetproject/ghost#31]
after change root permission by following command 
# chmod +x install.sh 
then run command > ./install.sh after a few second came up with No internet connection !
However there is fast broadband internet connection and i have check twice that internet is connected. 
I'm using Kali Linux latest version on Oracle virtual box. 

Any idea to fix this issue ??

**Comment by monk249** [comment]
I have the same problem

**Comment by monk249** [comment]
> 通过以下命令更改root权限后
> 
> # chmod + x install.sh
> 然后几秒钟后，运行命令> ./install.sh，提示没有互联网连接！
> 但是有快速的宽带互联网连接，我已经检查过两次互联网连接了。
> 我在Oracle虚拟机上使用的是Kali Linux最新版本。
> 
> 任何解决此问题的想法？



I found a solution

**Comment by monk249** [comment]
> 通过以下命令更改root权限后
> 
> # chmod + x install.sh
> 然后几秒钟后，运行命令> ./install.sh，提示没有互联网连接！
> 但是有快速的宽带互联网连接，我已经检查过两次互联网连接了。
> 我在Oracle虚拟机上使用的是Kali Linux最新版本。
> 
> 任何解决此问题的想法？


I have the same problem
I found a solution
Modify google.com in install.sh

**Comment by enty8080** [comment]
Why you need to modify google.com????
