### ISSUE TITLE
Server issue

### ISSUE THREAD

**Issue by rpmsufiyan123** [entynetproject/ghost#33]
After Sudo ghost.
Its Shows Failed to start Ghost server.

**Comment by LogicatedDev** [comment]
I get the same issue as you, if you figure a fix please dm my discord Greever#5904

**Comment by lalitsharma007** [comment]
i also geting the same issue as yours,if any of you fixes is dm on instagram (sharma_lalit45)

**Comment by enty8080** [comment]
Execute `./install.sh`
