### ISSUE TITLE
error while connecting to ip

### ISSUE THREAD

**Issue by jilalitajdine** [entynetproject/ghost#36]
hi
here is the error i got when try to connect to ip

OS Parrot 4.8
adb is installed and server started
![Screenshot at 2020-05-02 23-28-27](https://user-images.githubusercontent.com/19841512/80894758-fbe17180-8cd5-11ea-9d93-6cbf8059b606.png)
![Screenshot at 2020-05-02 23-28-57](https://user-images.githubusercontent.com/19841512/80894761-013ebc00-8cd6-11ea-9146-01359534de10.png)

**Comment by vlpontes** [comment]
No need of the port number. Try "connect 198.58.105.17

**Comment by kattasainaveen** [comment]
please help

*] Connecting to 182.185.240.214...
[-] Failed to connect to 182.185.240.214!

**Comment by enty8080** [comment]
Maybe invalid ip
