### ISSUE TITLE
Failed to start Ghost Server my resolve

### ISSUE THREAD

**Issue by normandy36** [entynetproject/ghost#37]
I read the thread here on this subject and it was closed with run the install.sh,  I found that did not work on my Kali machines,  I went through the install script and found that

apt-get -y install adb -   did not work.

The line in the ghost script that displays that error is
def start_server():
    adb = os.popen("which adb").read()
    if adb.strip("\n") == "":
        print(E+"Failed to start Ghost Server!")
        sys.exit()
    else:
        os.system("chmod +x core/server.sh && core/server.sh")

I resolved this by changing the sources.list file and added the following.

deb http://http.kali.org/kali kali-rolling main contrib non-free
# For source package access, uncomment the following line
# deb-src http://http.kali.org/kali kali-rolling main contrib non-free
deb http://http.kali.org/kali sana main non-free contrib
deb http://security.kali.org/kali-security sana/updates main contrib non-free
# For source package access, uncomment the following line
# deb-src http://http.kali.org/kali sana main non-free contrib
# deb-src http://security.kali.org/kali-security sana/updates main contrib non-free
deb http://old.kali.org/kali moto main non-free contrib
# For source package access, uncomment the following line
# deb-src http://old.kali.org/kali moto main non-free contrib

After that it worked.

**Comment by justmvg** [comment]
What's with this heading/non-heading styling? Could you clear up the instruction a bit?

**Comment by arun312** [comment]
how to find sources.list file

**Comment by arun312** [comment]
> up

did that work?
