### ISSUE TITLE
cant connect ip and here is the command u wanted

### ISSUE THREAD

**Issue by heydrickanonymous-cyber** [entynetproject/ghost#39]
ghost> connect 193.163.1.79:5555
[*] Connecting to 193.163.1.79:5555...
[-] Failed to connect to 193.163.1.79:5555!
ghost> connect 193.163.1.79
[*] Connecting to 193.163.1.79...
[-] Failed to connect to 193.163.1.79!
ghost> 

-------------------------------------------------------------------------------------------------
i have changed my ip in here for privacy reasons.

**Comment by vlpontes** [comment]
Try to ping your IP. I know some IPs have ping "disabled" but I think it would be the first try. Don't need to type the port number. 
Try "connect 121.157.123.57". I've tried this here and worked.

**Comment by Davidsouza20** [comment]
I Tried to ping the ip and ping normally but when I try to connect I get the same error above.

**Comment by heydrickanonymous-cyber** [comment]
it pings to the ip but when i do this 
----------------------------------------------------------------
ghost> connect 192.168.1.79
[*] Connecting to 192.168.1.79...
[-] Failed to connect to 192.168.1.79!
ghost> 
------------------------------------------------------------------
i still get the same error the device is in my local network, ip has been changed for privacy reasons.

**Comment by heydrickanonymous-cyber** [comment]
i have 2 phones of Samsung A20
i am able to connect in one but i cant connect in other one, even tho they both are on same network and have same settings in them.

**Comment by heydrickanonymous-cyber** [comment]
it wokes sometime in one device and sometime dont
ghost> connect 192.168.1.79
[*] Connecting to 192.168.1.79...
[-] Failed to connect to 192.168.1.79!
ghost> connect 192.168.1.77
[*] Connecting to 192.168.1.77...
[-] Failed to connect to 192.168.1.77!
now it don't connect to either of my devices

**Comment by enty8080** [comment]
You should enable wireless debug (adb) in the developer settings
