### ISSUE TITLE
failed to start ghost server

### ISSUE THREAD

**Issue by sriramana007** [entynetproject/ghost#4]
after the successful installation ghost framework in kali linux 2020 ...it shows "failed to start ghost server"..

**Comment by enty8080** [comment]
run: `apt-get install adb`

**Comment by sriramana007** [comment]
After installing adb again I installed ghost frame work ...server too started but options or features are not showing..
![Uploading IMG_20200403_163909619_HDR.jpg…]()

**Comment by sriramana007** [comment]
I had installed adb driver..and installed ghost framework..server started but options are not showing
![Uploading IMG_20200403_163909619_HDR.jpg…]()

**Comment by enty8080** [comment]
Seriously? Use `help` command to view all available options. There is an example in the README.md.

**Comment by sriramana007** [comment]
I didn't modify anything bro ...if I give help command only core commands
are coming...

**Comment by enty8080** [comment]
Yes, to view device commands you should first connect target device!

**Comment by enty8080** [comment]
Type: `connect <ip>` and after this Ghost Framework will open device menu with device commands such as `shell` or `screenshot`.

**Comment by sriramana007** [comment]
Ok bro thanks a lot

**Comment by enty8080** [comment]
You can test it with your own device or try searching for vulnerable device IPs here: https://shodan.io/

**Comment by sriramana007** [comment]
Bro but without connecting any target device with abd..we cannot access the
device alone with its ip address..am I right

**Comment by enty8080** [comment]
Ghost Framework's `connect <ip>` command will call `adb connect <ip>`. Ghost Framework is an ADB automatization.

**Comment by enty8080** [comment]
I mean that you don't need to connect device via adb and after this via Ghost.

**Comment by enty8080** [comment]
Can I close this issue?

**Comment by sriramana007** [comment]
Yeah bro..sure.. thanks for that

**Comment by anjinaikk** [comment]
* failed to start daemon
error: cannot connect to daemon
[-] Failed to connect to 26.63.7.121!

![Screenshot_20200509-050740]
(https://user-images.githubusercontent.com/65050291/81457263-0a86c780-91b3-11ea-95cd-afaae726562b.png)
