### ISSUE TITLE
Failed to start the server

### ISSUE THREAD

**Issue by cbhushan051** [entynetproject/ghost#40]
I simply typedghost in terminal to start ghost, but it fails to start the server, even though I gave as the superuser also but still it is same.
![Screenshot from 2020-05-04 05-00-48](https://user-images.githubusercontent.com/36883519/80928778-548f3800-8dc4-11ea-9874-7173961ad0da.png)
![Screenshot from 2020-05-04 05-00-28](https://user-images.githubusercontent.com/36883519/80928784-5822bf00-8dc4-11ea-83b0-0e6c02312119.png)

**Comment by montejano5** [comment]
Same here

**Comment by vlpontes** [comment]
How did you install ghost?

**Comment by cbhushan051** [comment]
> How did you install ghost?

Same way as provided in instruction or you can simply download this repository and install it using given command.

**Comment by cbhushan051** [comment]
This problem has been corrected earlier so follow this [link](https://github.com/entynetproject/ghost/issues/37)
