### ISSUE TITLE
Launch app

### ISSUE THREAD

**Issue by c0-sudo** [entynetproject/ghost#41]
https://github.com/entynetproject/ghost/issues/26#issuecomment-622563315 

Even with full app names, `com.android.xxx` ghost doesn't find any App.

Kind Regards

**Comment by enty8080** [comment]
Execute ‘apps’ and find your app

**Comment by c0-sudo** [comment]
`ghost(XX.XXX.XXX.XX)> apps
com.android.soundrecorder
com.myapp
com.android.defcontainer
com.example.android.notepad
com.android.quicksearchbox
com.android.contacts
com.android.inputmethod.latin
com.android.phone
com.google.android.partnersetup
com.android.calculator2
com.android.proxyhandler
com.android.htmlviewer
com.google.android.gsf.login
com.android.providers.calendar
com.android.inputdevices
com.uncube.account
com.android.calendar
com.android.browser
com.android.music
com.lilithgame.roc.gp
com.android.onetimeinitializer
com.android.providers.downloads.ui
com.android.providers.userdictionary
com.android.documentsui
com.android.sharedstoragebackup
com.android.camera2
com.android.vpndialogs
com.google.android.configupdater
com.android.pacprocessor
com.android.providers.media
com.android.certinstaller
com.android.basicsmsreceiver
com.google.android.gms
com.android.printspooler
com.google.android.setupwizard
com.android.gallery
com.google.android.syncadapters.calendar
android
com.android.settings
com.android.providers.contacts
com.google.android.apps.uploader
com.android.externalstorage
com.android.vending
com.google.android.play.games
com.android.systemui
com.hotheadgames.google.free.bigwinfootball2
com.google.home.tv
com.android.wallpaper.livepicker
com.android.keychain
com.android.packageinstaller
com.google.android.backuptransport
com.android.providers.telephony
com.svox.pico
com.location.provider
com.android.dialer
com.android.deskclock
com.android.location.fused
com.android.wallpapercropper
com.android.backupconfirm
com.android.providers.settings
com.google.android.gsf
cmf0.c3b5bm90zq.patch
com.android.keyguard
eu.nordeus.topeleven.android
com.android.shell
com.android.providers.downloads
com.google.android.syncadapters.contacts
com.android.musicfx
ghost(XX.XXX.XXX.XX)> launch com.android.musicfx
[-] Application is not found!`

I've already done that, still doesn't work. :)

**Comment by enty8080** [comment]
I am going to fix this

**Comment by aokil** [comment]
When you lift upload application In this path, for example /system/bin/sh/
I find and everything is fine
but wehn i install

[-] Local file: /system/bin/client/client.apk: does not exist!
Is there any solution

**Comment by aokil** [comment]
> I am going to fix this

When you lift upload application In this path, for example /system/bin/sh/
I find and everything is fine
but wehn i install

[-] Local file: /system/bin/client/client.apk: does not exist!
Is there any solution

**Comment by c0-sudo** [comment]
> I am going to fix this

Thanks, super fresh tool by the way !  :)

**Comment by enty8080** [comment]
@aokil , please send me full command
