### ISSUE TITLE
Connecting to device but showing as Error: device offline 

### ISSUE THREAD

**Issue by bybandla** [entynetproject/ghost#42]
Hi there, 
I'm trying to connect my personal device with the IPV4 address from www.myipaddress.com and it is connecting. But while using commands, it giving me an error "Error: device offline".

Attached image FYI.

![Screenshot (15)](https://user-images.githubusercontent.com/21012127/80956559-16733200-8e1f-11ea-8143-619a9181a42c.png)

**Comment by enty8080** [comment]
Just reconnect or use another device, that means that the device offline

**Comment by bybandla** [comment]
But as I mentioned it is my own device and there is a proper internet connection, ADB is also enabled from the developer options.

**Comment by Pawankrishnabandla** [comment]
mine is showing some error to connect can i some help from u???????

Traceback (most recent call last):
  File "./ghost", line 27, in <module>
    import readline
ModuleNotFoundError: No module named 'readline
 this is my error msg
