### ISSUE TITLE
Failed to start Ghost Server

### ISSUE THREAD

**Issue by TheEeki** [entynetproject/ghost#44]
I'm having this error `[-] Failed to start Ghost Server !`. Why is this happening and how can I fix that?

**Comment by cbhushan051** [comment]
> I'm having this error `[-] Failed to start Ghost Server !`. Why is this happening and how can I fix that?

go to this [link](https://github.com/entynetproject/ghost/issues/37)

**Comment by TheEeki** [comment]
Does that work for Ubuntu also?
