### ISSUE TITLE
install

### ISSUE THREAD

**Issue by aokil** [entynetproject/ghost#46]
When you lift upload application In this path, for example /system/bin/sh/
I find and everything is fine
but wehn i install 

[-] Local file: /system/bin/client/client.apk: does not exist!
Is there any solution

**Comment by enty8080** [comment]
@aoki, please send me full command

**Comment by enty8080** [comment]
Oh, this is not an error, you should to make this:

`install <your_local_path_to_apk>`

**you don't need to upload apk using `upload`, just use `install <local_path>`**

**Comment by enty8080** [comment]
use `install client.apk`
