### ISSUE TITLE
Launching Ghost

### ISSUE THREAD

**Issue by MFahadGraphics** [entynetproject/ghost#47]
After installation every time when I try to start a Ghost this error came up. Anyone, Please Help.

_Traceback (most recent call last):
  File "./ghost", line 27, in <module>
    import readline
ModuleNotFoundError: No module named 'readline'_

**Comment by enty8080** [comment]
Just install readline

**Comment by Pawankrishnabandla** [comment]
even after installing readline also it's showing the same
