### ISSUE TITLE
Ghost don't work on my Wifi LAN

### ISSUE THREAD

**Issue by ivaregos** [entynetproject/ghost#48]
I install and probe over internet thats work fine, searching device with Shodan.
But is posible to work over my Wifi LAN?. My android device is turne on USB debug.

ghost> connect 192.168.100.217:5555
[*] Connecting to 192.168.100.217:5555...
[-] Failed to connect to 192.168.100.217:5555!

**Comment by enty8080** [comment]
Do NOT use the port, just IP:
`connect 192.168.100.217`
