### ISSUE TITLE
failed to start server

### ISSUE THREAD

**Issue by tushant0070** [entynetproject/ghost#5]
the server is not starting
![Screenshot 2020-04-03 19:29:44](https://user-images.githubusercontent.com/63095707/78340253-673f0300-75b3-11ea-850b-b219e8d310e9.png)

**Comment by enty8080** [comment]
What OS do you use?

**Comment by enty8080** [comment]
run: `apt-get install adb`

**Comment by tushant0070** [comment]
![Screenshot 2020-04-04 19:14:29](https://user-images.githubusercontent.com/63095707/78422103-79d03f80-767a-11ea-9cd1-014eba955d33.png)

**Comment by tushant0070** [comment]
why it is not?????
