### ISSUE TITLE
no module named readline

### ISSUE THREAD

**Issue by DreadFog** [entynetproject/ghost#50]
i did the pip3 install readline that you told the other guy, but it still says the module is missing
Proof : 
```
root@DESKTOP-3PKQ18O:~# pip3 install readline
Requirement already satisfied: readline in /usr/local/lib/python3.8/dist-packages (6.2.4.1)
```
any idea?

**Comment by DreadFog** [comment]
I also tried uninstalling and reinstalling, even through the ol' pip 
```
root@DESKTOP-3PKQ18O:~# ghost
Traceback (most recent call last):
  File "./ghost", line 27, in <module>
    import readline
ModuleNotFoundError: No module named 'readline'
root@DESKTOP-3PKQ18O:~# pip install readline
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting readline
  Using cached readline-6.2.4.1.tar.gz (2.3 MB)
Building wheels for collected packages: readline
  Building wheel for readline (setup.py) ... done
  Created wheel for readline: filename=readline-6.2.4.1-cp27-cp27mu-linux_x86_64.whl size=358476 sha256=907236e5f2aab5549cc85fe1df9312fb512af7918ab7017e3dac6bba65245c31
  Stored in directory: /root/.cache/pip/wheels/b9/fe/16/7b2f5b62e83a3913db1ff68d8040ff155fc932c94c6a0ab735
Successfully built readline
Installing collected packages: readline
Successfully installed readline-6.2.4.1
WARNING: You are using pip version 20.0.2; however, version 20.1 is available.
You should consider upgrading via the '/usr/bin/python -m pip install --upgrade pip' command.
root@DESKTOP-3PKQ18O:~# ghost
Traceback (most recent call last):
  File "./ghost", line 27, in <module>
    import readline
ModuleNotFoundError: No module named 'readline'
root@DESKTOP-3PKQ18O:~# pip~ uninstall readline
bash: pip~: command not found
root@DESKTOP-3PKQ18O:~# pip3 uninstall readline
Uninstalling readline-6.2.4.1:
  Would remove:
    /usr/local/lib/python3.8/dist-packages/readline-6.2.4.1.dist-info/*
    /usr/local/lib/python3.8/dist-packages/readline.cpython-38-x86_64-linux-gnu.so
Proceed (y/n)? y
  Successfully uninstalled readline-6.2.4.1
root@DESKTOP-3PKQ18O:~# sudo pip3 install readline
Collecting readline
  Cache entry deserialization failed, entry ignored
Installing collected packages: readline
Successfully installed readline-6.2.4.1
root@DESKTOP-3PKQ18O:~# ghost                                                                                     
Traceback (most recent call last):                                                                                
  File "./ghost", line 27, in <module>                                                                            
    import readline                                                                                               
ModuleNotFoundError: No module named 'readline'                                                                   
root@DESKTOP-3PKQ18O:~#     
```

**Comment by RoHBee** [comment]
TRY THIS:
sudo apt-get install libncurses5-dev
sudo -H pip3 install readline

**Comment by RoHBee** [comment]
> I also tried uninstalling and reinstalling, even through the ol' pip
> 
> ```
> root@DESKTOP-3PKQ18O:~# ghost
> Traceback (most recent call last):
>   File "./ghost", line 27, in <module>
>     import readline
> ModuleNotFoundError: No module named 'readline'
> root@DESKTOP-3PKQ18O:~# pip install readline
> DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
> Collecting readline
>   Using cached readline-6.2.4.1.tar.gz (2.3 MB)
> Building wheels for collected packages: readline
>   Building wheel for readline (setup.py) ... done
>   Created wheel for readline: filename=readline-6.2.4.1-cp27-cp27mu-linux_x86_64.whl size=358476 sha256=907236e5f2aab5549cc85fe1df9312fb512af7918ab7017e3dac6bba65245c31
>   Stored in directory: /root/.cache/pip/wheels/b9/fe/16/7b2f5b62e83a3913db1ff68d8040ff155fc932c94c6a0ab735
> Successfully built readline
> Installing collected packages: readline
> Successfully installed readline-6.2.4.1
> WARNING: You are using pip version 20.0.2; however, version 20.1 is available.
> You should consider upgrading via the '/usr/bin/python -m pip install --upgrade pip' command.
> root@DESKTOP-3PKQ18O:~# ghost
> Traceback (most recent call last):
>   File "./ghost", line 27, in <module>
>     import readline
> ModuleNotFoundError: No module named 'readline'
> root@DESKTOP-3PKQ18O:~# pip~ uninstall readline
> bash: pip~: command not found
> root@DESKTOP-3PKQ18O:~# pip3 uninstall readline
> Uninstalling readline-6.2.4.1:
>   Would remove:
>     /usr/local/lib/python3.8/dist-packages/readline-6.2.4.1.dist-info/*
>     /usr/local/lib/python3.8/dist-packages/readline.cpython-38-x86_64-linux-gnu.so
> Proceed (y/n)? y
>   Successfully uninstalled readline-6.2.4.1
> root@DESKTOP-3PKQ18O:~# sudo pip3 install readline
> Collecting readline
>   Cache entry deserialization failed, entry ignored
> Installing collected packages: readline
> Successfully installed readline-6.2.4.1
> root@DESKTOP-3PKQ18O:~# ghost                                                                                     
> Traceback (most recent call last):                                                                                
>   File "./ghost", line 27, in <module>                                                                            
>     import readline                                                                                               
> ModuleNotFoundError: No module named 'readline'                                                                   
> root@DESKTOP-3PKQ18O:~#     
> ```

TRY THIS:
sudo apt-get install libncurses5-dev
sudo -H pip3 install readline

**Comment by enty8080** [comment]
Or you can install `apt-get install libreadline6-dev`
