### ISSUE TITLE
Not an apk file

### ISSUE THREAD

**Issue by RoHBee** [entynetproject/ghost#51]
Hello dev
I recently got not an apk error if its an rror then please solve it or if its my mistake then how to properly use INSTALL command

**Comment by RoHBee** [comment]
No one will help you bro

**Comment by RoHBee** [comment]
Not yet

**Comment by RoHBee** [comment]
Help this user ANYONE???

**Comment by RoHBee** [comment]
PLEASE PLEASE PLEASE

**Comment by enty8080** [comment]
hi, I fixed this error, try reinstall
