### ISSUE TITLE
user

### ISSUE THREAD

**Issue by Dark-angel31** [entynetproject/ghost#54]
NOT CONNECTING TO IP

**Comment by dolhack** [comment]
same problem

**Comment by hrupesh** [comment]
I have the same issue.
The framework is not connecting to any IP and could not connect error message is being displayed.
Can anyone explain what is happening?
I cross checked the connection to the android device by pinging it and the response was positive.
@enty8080 @Dark-angel31 @dolhack

**Comment by enty8080** [comment]
Target Device should has adb enabled
