### ISSUE TITLE
Failed to start Ghost Server

### ISSUE THREAD

**Issue by pranaypaine** [entynetproject/ghost#58]
Ghost server failed to start.
I tried installing it multiple times.
Nothing happened.

**Comment by pranaypaine** [comment]
@enty8080

**Comment by enty8080** [comment]
Install adb

**Comment by pranaypaine** [comment]
@enty8080 I have added an update in the readme for Prerequisites.
#62 
You can review it and merge it.

**Comment by enty8080** [comment]
What OS do you use? File install.sh should install all requirements, if you want me to merge your PR, add installation string to install.sh.

**Comment by pranaypaine** [comment]
I was using kali linux on a virtual machine.

**Comment by pranaypaine** [comment]
@enty8080 Sure I'll add install strings in install.sh

**Comment by pranaypaine** [comment]
@enty8080 this works in kali linux.
`apt-get -y install android-tools-adb`
now able to start ghost using this.

**Comment by pranaypaine** [comment]
#63

**Comment by rajahammad123** [comment]
enty 8080 when i connect to target device in ghost it says failed to conenct how to fix it
