### ISSUE TITLE
Installation error (says no internet connection)

### ISSUE THREAD

**Issue by AnonCYTO** [entynetproject/ghost#59]
I've cloned into this repository and downloaded ghost,
Run `chmod +x install.sh`
And when I execute(as root) `./install.sh`,
This happens.

![Screenshot_20200507-045521](https://user-images.githubusercontent.com/39458214/81238306-50ab2200-901f-11ea-89cb-886f3b74541d.png)

Also, note that I have a good and stable internet connection, and I've also installed adb.

What am I supposed to do here? Am I missing any prerequisites or tools? 

Someone please help.

**Comment by Akthar303** [comment]
Hey i too encountered the same issue then i resolved by restarting network manager
` kali@kali:`$ sudo service networking restart `
and then again run
` kali@kali:`$ sudo service network-manager restart `
this might resolve your problem 
if this doesn't then retry connecting your internet

**Comment by AnonCYTO** [comment]
@Akthar303 , I've tried everything that you suggested. (Still ended up with the same error)
Even changed to Google's DNS servers for stability. (Still ended up with the same error)
Treated my wireless connection as metered. 
And and even then, the same error.

At this point I seriously suspect I'm missing something here.

**Comment by CYPHERSHAW** [comment]
yeah im too facing the same problem

**Comment by enty8080** [comment]
If you are using VM, modify install.sh and remove the internet connection checker.

**Comment by CYPHERSHAW** [comment]
How can I do it?

**Comment by CYPHERSHAW** [comment]
@enty8080 I didn't understand the solution given by you can you please explain the procedure? Please?
