### ISSUE TITLE
free(): invalid pointer Aborted

### ISSUE THREAD

**Issue by Akthar303** [entynetproject/ghost#60]
I recently installed ghost framework without any error but when i run any command i encounter this error

`

     .-.
     .'   `.
    :0 0  :
    : o    `.
   :         ``.
  :             `.
 :  :         .   `.
 :   :          ` . `.
  `.. :            `. ``;
     `:;             `:'
        :              `.
         `.              `.     
           `'`'`'`---..,___`.

Ghost Framework v5.0
--------------------

```
ghost> help
free(): invalid pointer
/usr/local/bin/ghost: line 85: 11249 Aborted  
```
`
PS: I have stable internet connection, adb installed & kali with perfect dependencies
help me to resolve @enty8080 @enty8080 
and it would be good if you specify the requirements in README.md

Thank you :)

**Comment by enty8080** [comment]
Problem not in Ghost, Problem in your environment, OS or computer. `free(): invalid pointer` is not a Python error that means that problem not in Ghost

**Comment by enty8080** [comment]
https://stackoverflow.com/questions/20297524/c-free-invalid-pointer

**Comment by game-lover** [comment]
pip3 install gnureadline
