### ISSUE TITLE
No module named 'readline'

### ISSUE THREAD

**Issue by G-nome-byte** [entynetproject/ghost#61]
root@kali:~# ghost
Traceback (most recent call last):
  File "./ghost", line 27, in <module>
    import readline
ModuleNotFoundError: No module named 'readline'
root@kali:~# 

**I have tried the following but still couldn't get it to work:**

1. pip install pyreadline
2. python -m pip install pyreadline
3. Going into ghost file, then seeing what it uses as readline.  removed the readline dependency from pip_console.py. ( It comletely made it inpossible to even launch the program so i had to undo. It was worth a try.)
4. installing files and updating files to see if i was missing pakages.
5. uninstalling and reinstalling....
6. python3 -m pip install deadline
7. pip3 install deadline
I hope theres something i could do to fix this but i need your help.

**Comment by enty8080** [comment]
Install readline via apt-get, libreadline

**Comment by G-nome-byte** [comment]
Is there a specific command for this? Because im either getting error messages or invalid commands.

**Comment by enty8080** [comment]
`apt-get search readline`
`apt-get install libreadline6-dev`

**Comment by G-nome-byte** [comment]
@enty8080 welll, thank you so much for all your help but it just seems the problem wont go away.Its a really really well made tool and i just want to say brilliant work.

**Comment by kingloard** [comment]
Traceback (most recent call last):
  File "./ghost", line 456, in <module>
    main()
  File "./ghost", line 58, in main
    if ui[0] == "exit":
IndexError: list index out of range




help me

**Comment by Koolteen1** [comment]
Same

**Comment by Pawankrishnabandla** [comment]
> Traceback (most recent call last):
> File "./ghost", line 456, in
> main()
> File "./ghost", line 58, in main
> if ui[0] == "exit":
> IndexError: list index out of range
> 
> help me

yeah same problem for me also but with 27th line

**Comment by Pawankrishnabandla** [comment]
error in 27th line readline
