### ISSUE TITLE
Failed to connect

### ISSUE THREAD

**Issue by LukasAlstrup** [entynetproject/ghost#65]
Hello guys!
Thanks in advance.
This is my first time using this tool, and I can't get it up and running.
 I'm following this tutorial https://www.youtube.com/watch?v=0eAafqElwik by Loi Liang Yang.
I come to 4:30 in the video and then the errors comes. I have pasted my "Ghost Framework Console" below:
(My Huawei phones IP was 192.168.1.107)

     .-.
    .'   `.
    :0 0  :
    : o    `.
   :         ``.
  :             `.
 :  :         .   `.
 :   :          ` . `.
  `.. :            `. ``;
     `:;             `:'
        :              `.
         `.              `.     
           `'`'`'`---..,___`.

Ghost Framework v5.0
--------------------

ghost> help

Core Commands
=============

    Command        Description
    -------        -----------
    clear          Clear terminal window.
    disconnect     Disconnect from target device.
    connect        Connect to target device.
    exit           Exit Ghost Framework.
    help           Show available commands.
    update         Update Ghost Framework.

ghost> shell
[-] Unrecognized command!
ghost> help

Core Commands
=============

    Command        Description
    -------        -----------
    clear          Clear terminal window.
    disconnect     Disconnect from target device.
    connect        Connect to target device.
    exit           Exit Ghost Framework.
    help           Show available commands.
    update         Update Ghost Framework.

ghost> connect 192.168.1.107:5555
[*] Connecting to 192.168.1.107:5555...
[-] Failed to connect to 192.168.1.107:5555!
ghost> connect 192.168.1.76:5555
[*] Connecting to 192.168.1.76:5555...
[-] Failed to connect to 192.168.1.76:5555!
ghost> connect 192.168.1.1:5555
[*] Connecting to 192.168.1.1:5555...
[-] Failed to connect to 192.168.1.1:5555!
ghost> connect 192.168.1.0:5555
[*] Connecting to 192.168.1.0:5555...
[-] Failed to connect to 192.168.1.0:5555!
ghost> connect 192.168.1.107:33484
[*] Connecting to 192.168.1.107:33484...
[-] Failed to connect to 192.168.1.107:33484!
ghost>

**Comment by LukasAlstrup** [comment]
I tried turning on mobile data and used my phones public IP and that did not work either

**Comment by enty8080** [comment]
**You don't need to type `:<port>` define just IP**
`connect 192.168.1.107`

**Comment by Lokii808** [comment]
eu to com o error 

traceback

file ''gohost'', line 27, in <module>
import readline

modulenotfounderror: no modulenamed 'readline''

**Comment by mad9640** [comment]
When try to connect it is showing failed to connect pls help me thanks

**Comment by GRMams** [comment]
got the same error `Failed to connect to *********`, do you have a clue where that could be coming from ?

**Comment by baibhav470** [comment]
![Screenshot_2020-10-04_11-55-08](https://user-images.githubusercontent.com/72139567/95020334-7d984b00-0638-11eb-8d74-199104ed560a.png)
need help

**Comment by Raghava-123** [comment]
bro i also got the same problem: "Failed to connect to 2401!" what is the solution for this

**Comment by miroumdx** [comment]
bro i also got the same problem: "Failed to connect to 2401!" what is the solution for this
