### ISSUE TITLE
Apps not installing

### ISSUE THREAD

**Issue by Jackandrichardjunior** [entynetproject/ghost#72]
sh: 1: core/apps/install.sh: not found

**Comment by MohamedMarzouk23** [comment]
try to go to this path and check if this file is exist or not.

**Comment by Jackandrichardjunior** [comment]
Yeah! They all exist and I've Give them permission to run.

**Comment by Jackandrichardjunior** [comment]
But, I cannot install...I am not telling you that is fixed...I am telling that that happens even if the files exists :rofl:
