### ISSUE TITLE
Installation problem.

### ISSUE THREAD

**Issue by parikshitlfj12** [entynetproject/ghost#76]
While installing the the ghost framework. We run ./install.sh and its saying no internet connection. But my internet connection is all fine.

**Comment by enty8080** [comment]
Do you use a VM?

**Comment by parikshitlfj12** [comment]
Yes.

**Comment by enty8080** [comment]
Ok. There is a problem with communication. On VM: Try to go to the browser and search for google.com

**Comment by enty8080** [comment]
Or ping google.com

**Comment by enty8080** [comment]
VM terminal:
ping google.com

**Comment by parikshitlfj12** [comment]
On browser its working fine but can't ping from the terminal. I don't know why.

**Comment by parikshitlfj12** [comment]
More precisely i can ping a hostname but cant ping an IP

**Comment by VedanthiKarthik** [comment]
> More precisely I just can't ping google.com
> Everything else is good.
But when u stop ping google.com, you may see the number of packets received/ transmitter. Please do check it once. Same thing happened to me earlier

**Comment by VedanthiKarthik** [comment]
Even I am facing the same issue of installing on VM. But the internet connection is fine

**Comment by parikshitlfj12** [comment]
Hey this issue isn't solved. How can you close this

**Comment by enty8080** [comment]
@parikshitlfj12 Please execute `nslookup google.com &> /dev/null; echo $?` on you VM, what does it returns?

**Comment by enty8080** [comment]
@parikshitlfj12 also try to ping www.google.com

**Comment by enty8080** [comment]
@parikshitlfj12 also try to ping another site you know.

**Comment by enty8080** [comment]
This can help me to understand the error.

**Comment by enty8080** [comment]
And also try to ping 8.8.8.8
I am waiting for results

**Comment by marutidavari** [comment]
I have installed it but issue is
"failed to connect" error.
I am using it in virtual machine.
Trying to connect my own device.
OS: Kali Linux 2020

**Comment by parikshitlfj12** [comment]
Ya i can ping all other websites except google. And my network connection is fine

**Comment by enty8080** [comment]
Can you ping www.google.com, not just google.com, with www?

**Comment by enty8080** [comment]
@parikshitlfj12 try to ping 8.8.8.8

**Comment by parikshitlfj12** [comment]
Yeah. I can do that

**Comment by enty8080** [comment]
You can ping www.google.com?

**Comment by parikshitlfj12** [comment]
Yeah

**Comment by enty8080** [comment]
Good. The problem will be fixed today. I will change url google.com to www.google.com

**Comment by enty8080** [comment]
Thank you for help.

**Comment by enty8080** [comment]
Execute it on your VM:

`ping -c 1 -q www.google.com >&/dev/null; echo $?`

What it returns?

**Comment by enty8080** [comment]
@parikshitlfj12 

> Execute it on your VM:
> 
> `ping -c 1 -q www.google.com >&/dev/null; echo $?`
> 
> What it returns?

**Comment by parikshitlfj12** [comment]
0

**Comment by mc-mvnchu** [comment]
Just got the same problem... i.e:
After executing "./install.sh" it's returns **no internet connection**
After reading this issue, I executed this command:
" ping -c 1 -q www.google.com >&/dev/null; echo $?] " it returns **1**
How can I fix this problem, immediately?
Btw, i am using kali linux os-release _2020.2_ **not VM**

**Comment by parikshitlfj12** [comment]
Can anyone tell what exactly this command does?

**Comment by enty8080** [comment]
Check internet connection, this command returns 0 if connected, other if not.

**Comment by enty8080** [comment]
@mc-mvnchu execute `ping -c 1 -q www.myip.com >&/dev/null; echo $?`

**Comment by parikshitlfj12** [comment]
What's this &/dev/null doing? This only.

**Comment by mc-mvnchu** [comment]
Due to the issues I currently have,
@parikshitlfj12 I had to open the code from **ghost** and I saw the _/dev/null_ embedded in the source code a couple of times. It seems essential so that ghost framework can run.
more about &/dev/nul/ https://linuxhint.com/what_is_dev_null/

**Comment by enty8080** [comment]
> @mc-mvnchu execute `ping -c 1 -q www.myip.com >&/dev/null; echo $?`

EXECUTE

**Comment by enty8080** [comment]
I your VM

**Comment by mc-mvnchu** [comment]
@enty8080 executing... it returns _**1**_

**Comment by parikshitlfj12** [comment]
@mc-mvnchu this means there is a connection problem.

**Comment by mc-mvnchu** [comment]
@parikshitlfj12 how can I fix this?

**Comment by parikshitlfj12** [comment]
Can you ping any website through your terminal?
Use -> ping google.com
and tell what output it's showing.

**Comment by parikshitlfj12** [comment]
@mc-mvnchu You should see some packets being sent to the sever

**Comment by enty8080** [comment]
> @parikshitlfj12 Is it fixable?
> And if so, how can I fix this?

WHAT VM DO YOU USE?
1 means you are not connected to the internet.

**Comment by parikshitlfj12** [comment]
@enty8080 he's not on a VM.

**Comment by mc-mvnchu** [comment]
My internet connection seem to be working very Okay when I open a browser.
But when using the terminal, I just pinged google.com and it did not respond immediately. I had to use "Ctrl+C" to stop the ping. This is what it showed in the terminal after force close.

" _PING google.com (216.58.223.78) 56(84) bytes of data.

--- google.com ping statistics ---
268 packets transmitted, 0 received, 100% packet loss_ "

**Comment by parikshitlfj12** [comment]
@mc-mvnchu Try pinging some other site. 
Ping mysafetrip.com
Now tell what you're getting?

**Comment by mc-mvnchu** [comment]
@parikshitlfj12 I just pinged _mysafetrip.com_ .
Same problem as before i.e 100% packet loss

**Comment by parikshitlfj12** [comment]
Try. 
Sudo ping mysafetrip.com
If this is not working. Then there's some problem in network connectivity.

**Comment by mc-mvnchu** [comment]
@parikshitlfj12 I tried with sudo and without sudo.
Still the same result.

**Comment by parikshitlfj12** [comment]
Are you under a rounter?

**Comment by mc-mvnchu** [comment]
@parikshitlfj12 Yes, I am under a router. Wi-Fi connection to be precise. Should I try LAN connection too?

**Comment by parikshitlfj12** [comment]
There must be a firewall settings over there which is blocking your ICMP requests.

**Comment by enty8080** [comment]
I don't know how to fix this
Maybe problem in proxy, VM or router.
I use ping because it used in all Linux, OpenBSD, Unix systems.

**Comment by mc-mvnchu** [comment]
Thanks @parikshitlfj12 for the help just found the problem.
I had set the firewall active in the router's "Default Getway" setting.
Porblem solved!!! :fireworks:

**Comment by enty8080** [comment]
That means that I can leave ping www.google.com in checking internet connection?

**Comment by parikshitlfj12** [comment]
@mc-mvnchu sounds good.

**Comment by enty8080** [comment]
I fix problem, can I close the issue?

**Comment by parikshitlfj12** [comment]
Sure. You can

**Comment by king5300** [comment]
[]()
