### ISSUE TITLE
Error: Failed to start Ghost Server!

### ISSUE THREAD

**Issue by aamir-rehman** [entynetproject/ghost#78]
I m having issue after installing the ghost it say: Failed to start Ghost Server!

root@kali:: cd Desktop/ghost-master/
root@kali::: /Desktop/ghost-master# chmod +x install.sh 
root@kali:::/Desktop/ghost-master# ./install.sh 
      .-.
    .'   `.
    :0 0  :
    : o    `.
   :         ``.
  :             `.
 :  :         .   `.
 :   :          ` . `.
  `.. :            `. ``;
     `:;             `:'
        :              `.
         `.              `.     
           `'`'`'`---..,___`.

[*] Installing dependencies...
[+] Successfully installed!
root@kali:~/Desktop/ghost-master# ghost
[-] Failed to start Ghost Server!

Please suggest.

**Comment by muthubala13** [comment]
I also got the same issue After the installation when try to start ghost framework it says "failed to start Ghost Server"
please give some solution to solve the issue

**Comment by aamir-rehman** [comment]
I think I am using old version of kali and if I manual run below two commands it don't work due to 404 on dist list of kali

 apt-update 
apt-get -y install adb

I will try to use latest kali and will comment.

**Comment by aamir-rehman** [comment]
Yap it works on latest kali linux. Ghost Server was not restarting because of failed to install dependencies.
