### ISSUE TITLE
failed to load ghost server

### ISSUE THREAD

**Issue by srijangiri** [entynetproject/ghost#80]
please tell me how should i fix this problem also that what can be the ways to to get target information from which i can gain accesses to that phone

**Comment by enty8080** [comment]
You should install adb

**Comment by cosmicwanderer7** [comment]
solved install adb 
by using 

Following below instructions, you should be able to install ADB and Fastboot on your system easily.

These commands are same for all Debian based distros
Instructions to install Android Debug Bus (ADB)
Open a terminal and enter the following commandsto install ADB ,
First
**sudo apt-get update**
then
**sudo apt-get install android-tools-adb**
and for fastboot
sudo apt-get install android-tools-fastboot
and ghost will run sucessfully
