### ISSUE TITLE
IndexError

### ISSUE THREAD

**Issue by Koolteen1** [entynetproject/ghost#83]
Traceback (most recent call last):
File "./ghost", line 456, in
main()
File "./ghost", line 58, in main
if ui[0] == "exit":
IndexError: list index out of range

help me

**Comment by enty8080** [comment]
Can you send me command you enter?

**Comment by enty8080** [comment]
All commands

**Comment by saitama142** [comment]
same for me, when i try to turn the wifi on (turn the device online ) to luch shell
when i type the command wifi 

index error : list index out of range

**Comment by Koolteen1** [comment]
First open terminal 
Then 
Type ghost
Then interface open up
Then 
ghost> (me hits enter) 
Then this error shows up

**Comment by enty8080** [comment]
Your problem was fixed, reclone and install.

**Comment by Koolteen1** [comment]
Thankyou
