### ISSUE TITLE
Server Start Error

### ISSUE THREAD

**Issue by VedanthiKarthik** [entynetproject/ghost#86]
I'm using Kali Linux 2020 installed on VM
I've successfully installed ghost framework
But when I try to run command:
`sudo ghost`
I get the message:
`[-] Failed to start Ghost Server!`
please someone help me to solve this issue

**Comment by pIngR51** [comment]
me too!

**Comment by pIngR51** [comment]
but mine is running mac

**Comment by saitama142** [comment]
install adb

quick search on google how to install it and then retsart the command ghost, it work for me

**Comment by enty8080** [comment]
> but mine is running mac

```
brew install adb
```

**Comment by parikshitlfj12** [comment]
You can also use sudo apt-get install android-tools-adb

**Comment by Banginpadr** [comment]
hello im having the same problem i have adb in my mac how do i fix this?

**Comment by cosmicwanderer7** [comment]
Install adb

**Comment by VedanthiKarthik** [comment]
@parikshitlfj12  I'm getting
`E: Unable to locate package android-tools-adb`

**Comment by parikshitlfj12** [comment]
@VedanthiKarthik Use the following command. Respectively
1) sudo add-apt-repository universe && sudo apt-get update && android-tools-fastboot
2) sudo install android-tools-adb

**Comment by cosmicwanderer7** [comment]
> @parikshitlfj12 I'm getting
> `E: Unable to locate package android-tools-adb`

add repositories first
then login as root
go to filesystem
/etc/apt/sources.list:​
and open source.list in text editor and at the end add
**deb http://http.kali.org/kali kali-rolling main contrib non-free
deb-src http://http.kali.org/kali kali-rolling main contrib non-free**

open terminal and type in 
_apt-get update_
after that type in
_apt-get install android-tools-adb android-tools-fastboot_

**Comment by anveshdange** [comment]
> You can also use sudo apt-get install android-tools-adb

Thank you !! This worked with my Kali running on Virtual Box on MacOS. Thanks !!
