### ISSUE TITLE
ghost framework 

### ISSUE THREAD

**Issue by cosmicwanderer7** [entynetproject/ghost#87]
i was unable to run ghost frame work 
the both comand ran sucessfully
1.chmod +x install.sh
2. ./install.sh
but when i typed in sudo ghost
it say's
:~# ghost
[-] Failed to start Ghost Server!
 please HELP

**Comment by enty8080** [comment]
What is your os?

**Comment by rajahammad123** [comment]
i am also facing same issue when i type ghost in terminal it says failed to start ghost server how to fix it

**Comment by waton4617zx** [comment]
me too

**Comment by lokesh12-cyber** [comment]
ghost is not connecting to ip ....... are you really sure about this framework ....it this really work 

ghost> connect 192.168.42.129:6666
[*] Connecting to 192.168.42.129:6666...
[-] Failed to connect to 192.168.42.129:6666!

**Comment by parikshitlfj12** [comment]
@lokesh12-cyber Maybe the port you should use is 5555

**Comment by Banginpadr** [comment]
ok i just fix it all you have to do is "brew cask install android-platform-tools" run this command

**Comment by enty8080** [comment]
Stop using port, just execute:
```
connect <ip>
```
**Without port (:5555)**

**Comment by cosmicwanderer7** [comment]
> What is your os?

Kali linux
