### ISSUE TITLE
Free():invalid pointer Aborted

### ISSUE THREAD

**Issue by Colors-dot** [entynetproject/ghost#88]
When I'm in to the Framework itself and tried to execute the command "help" an error just pop out saying "Free(): invalid pointer Aborted. How Am I going to fix this, kindly need some help.

**Comment by enty8080** [comment]
Can you send me output?

**Comment by enty8080** [comment]
Try run `export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES` in your terminal, and rerun ghost

**Comment by enty8080** [comment]
@game-lover maybe you can help.

**Comment by game-lover** [comment]
@enty8080  You said that you don't need my help

**Comment by game-lover** [comment]
What OS do you use?

**Comment by enty8080** [comment]
@Colors-dot what OS do you use?

**Comment by game-lover** [comment]
@enty8080  Please, see this [issue](https://github.com/entynetproject/ghost/issues/112)

**Comment by enty8080** [comment]
@game-lover How is this related?

**Comment by enty8080** [comment]
I checked)

**Comment by enty8080** [comment]
@game-lover do you know what is it?

**Comment by game-lover** [comment]
@enty8080 I don't have to answer

**Comment by enty8080** [comment]
@game-lover Why?

**Comment by game-lover** [comment]
@enty8080 I don't have to answer

**Comment by enty8080** [comment]
```
You was offended that I deleted your useless comments. You know that there are more important things and you know that you did not help with anything, that's why I deleted them. I answered your question why I deleted your comments.
```

**Comment by enty8080** [comment]
@game-lover OK.
