### ISSUE TITLE
-] Failed to start Ghost Server!

### ISSUE THREAD

**Issue by tr4i4n** [entynetproject/ghost#9]
-] Failed to start Ghost Server!
SOme help nedeed please 
On kali linux is not starting

**Comment by DJELLOUL882001** [comment]
me too

**Comment by enty8080** [comment]
do you have Ghost Framework installed? (`chmod + install.sh && ./install.sh`)

**Comment by tr4i4n** [comment]
Yes

**Comment by tr4i4n** [comment]
[-] Failed to start Ghost Server!
 Sow i did the istalation like this
git clone https://github.com/entynetproject/ghost.git  
Then cd ghost 
then ls 
chmod +x install.sh 
./install 
But stil having that error i need some help maybe i did something wrong ?

**Comment by enty8080** [comment]
Very strange, it works well for me
Try installing dependencies:
`apt update && apt install adb`

**Comment by game-lover** [comment]
What operating system do you use?

**Comment by Shubhamkrkr** [comment]
done this to 
but still having the same error

**Comment by GRMams** [comment]
im still having the same issue. I uninstalled it + installed it back and did all the commands + ``apt update && apt `install`
but still having the same problem ...

**Comment by game-lover** [comment]
show me output of
```bash
which adb
```

**Comment by cyberbuddy62** [comment]
failed to start server plz help
