### ISSUE TITLE
banner.txt No such file or directory

### ISSUE THREAD

**Issue by giuseppeurso-eu** [entynetproject/ghost#97]
It seems Install.sh script fails on row 62 if git command is not already present on the operating system:

```
{
git clone https://github.com/entynetproject/ghost.git
} &> /dev/null

```
I did a test after downloading the release package ghost-5.0.tar.gz on a fresh Linux Fedora OS x86_64

```
## (as root)
$ tar -xf ghost-5.0.tar.gz
$ cd ghost-5.0
$ .install.sh
...
./install.sh: row 68: cd: /root/ghost: No such file or directory
cat: banner/banner.txt: No such file or directory

[*] Installing dependencies...
[+] Successfully installed!
```
I think that git clone of the project can be moved after the dependencies are installed.

**Comment by enty8080** [comment]
please send me full error

**Comment by enty8080** [comment]
Yes it needs git

**Comment by enty8080** [comment]
Thank you for report, I fixed this bug
